# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/runtime-7.18.9" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.18.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.18.9.tgz";
        sha512 = "lkqXDcvlFT5rvEjiu6+QYO+1GXrEHRo2LOtS7E4GtX5ESIZOgepqsZBVIj6Pv+a6zqsya9VCgiK1KAK4BvJDAw==";
      };
    };
    "@emotion/is-prop-valid-0.8.8" = {
      name = "_at_emotion_slash_is-prop-valid";
      packageName = "@emotion/is-prop-valid";
      version = "0.8.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/is-prop-valid/-/is-prop-valid-0.8.8.tgz";
        sha512 = "u5WtneEAr5IDG2Wv65yhunPSMLIpuKsbuOktRojfrEiEvRyC85LgPMZI63cr7NUqT8ZIGdSVg8ZKGxIug4lXcA==";
      };
    };
    "@emotion/memoize-0.7.4" = {
      name = "_at_emotion_slash_memoize";
      packageName = "@emotion/memoize";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/memoize/-/memoize-0.7.4.tgz";
        sha512 = "Ja/Vfqe3HpuzRsG1oBtWTHk2PGZ7GR+2Vz5iYGelAw8dx32K0y7PjVuxK6z1nMpZOqAFsRUPCkK1YjJ56qJlgw==";
      };
    };
    "@floating-ui/core-1.0.0" = {
      name = "_at_floating-ui_slash_core";
      packageName = "@floating-ui/core";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@floating-ui/core/-/core-1.0.0.tgz";
        sha512 = "sm3nW0hHAxTv3gRDdCH8rNVQxijF+qPFo5gAeXCErRjKC7Qc28lIQ3R9Vd7Gw+KgwfA7RhRydDFuGeI0peGq7A==";
      };
    };
    "@floating-ui/dom-1.0.0" = {
      name = "_at_floating-ui_slash_dom";
      packageName = "@floating-ui/dom";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@floating-ui/dom/-/dom-1.0.0.tgz";
        sha512 = "PMqJvY5Fae8HVQgUqM+lidprS6p9LSvB0AUhCdYKqr3YCaV+WaWCeVNBtXPRY2YIdrgcsL2+vd5F07FxgihHUw==";
      };
    };
    "@floating-ui/react-dom-1.0.0" = {
      name = "_at_floating-ui_slash_react-dom";
      packageName = "@floating-ui/react-dom";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@floating-ui/react-dom/-/react-dom-1.0.0.tgz";
        sha512 = "uiOalFKPG937UCLm42RxjESTWUVpbbatvlphQAU6bsv+ence6IoVG8JOUZcy8eW81NkU+Idiwvx10WFLmR4MIg==";
      };
    };
    "@floating-ui/react-dom-interactions-0.9.1" = {
      name = "_at_floating-ui_slash_react-dom-interactions";
      packageName = "@floating-ui/react-dom-interactions";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@floating-ui/react-dom-interactions/-/react-dom-interactions-0.9.1.tgz";
        sha512 = "LNWB7FvGn/mI4Gw4DKbt/VblEhQOe3LUljBwp6BayFC2hEe+vhUMq2ExPFwMkgpKpoZVQPRYU8ejCKffBY5UMQ==";
      };
    };
    "@headlessui/react-1.6.6" = {
      name = "_at_headlessui_slash_react";
      packageName = "@headlessui/react";
      version = "1.6.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@headlessui/react/-/react-1.6.6.tgz";
        sha512 = "MFJtmj9Xh/hhBMhLccGbBoSk+sk61BlP6sJe4uQcVMtXZhCgGqd2GyIQzzmsdPdTEWGSF434CBi8mnhR6um46Q==";
      };
    };
    "@heroicons/react-1.0.6" = {
      name = "_at_heroicons_slash_react";
      packageName = "@heroicons/react";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@heroicons/react/-/react-1.0.6.tgz";
        sha512 = "JJCXydOFWMDpCP4q13iEplA503MQO3xLoZiKum+955ZCtHINWnx26CUxVxxFQu/uLb4LW3ge15ZpzIkXKkJ8oQ==";
      };
    };
    "@hookform/resolvers-2.9.7" = {
      name = "_at_hookform_slash_resolvers";
      packageName = "@hookform/resolvers";
      version = "2.9.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hookform/resolvers/-/resolvers-2.9.7.tgz";
        sha512 = "BloehX3MOLwuFEwT4yZnmolPjVmqyn8VsSuodLfazbCIqxBHsQ4qUZsi+bvNNCduRli1AGWFrkDLGD5QoNzsoA==";
      };
    };
    "@juggle/resize-observer-3.3.1" = {
      name = "_at_juggle_slash_resize-observer";
      packageName = "@juggle/resize-observer";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@juggle/resize-observer/-/resize-observer-3.3.1.tgz";
        sha512 = "zMM9Ds+SawiUkakS7y94Ymqx+S0ORzpG3frZirN3l+UlXUmSUR7hF4wxCVqW+ei94JzV5kt0uXBcoOEAuiydrw==";
      };
    };
    "@motionone/animation-10.13.1" = {
      name = "_at_motionone_slash_animation";
      packageName = "@motionone/animation";
      version = "10.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@motionone/animation/-/animation-10.13.1.tgz";
        sha512 = "dxQ+1wWxL6iFHDy1uv6hhcPjIdOg36eDT56jN4LI7Z5HZRyLpq8x1t7JFQclo/IEIb+6Bk4atmyinGFdXVECuA==";
      };
    };
    "@motionone/dom-10.12.0" = {
      name = "_at_motionone_slash_dom";
      packageName = "@motionone/dom";
      version = "10.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@motionone/dom/-/dom-10.12.0.tgz";
        sha512 = "UdPTtLMAktHiqV0atOczNYyDd/d8Cf5fFsd1tua03PqTwwCe/6lwhLSQ8a7TbnQ5SN0gm44N1slBfj+ORIhrqw==";
      };
    };
    "@motionone/easing-10.13.1" = {
      name = "_at_motionone_slash_easing";
      packageName = "@motionone/easing";
      version = "10.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@motionone/easing/-/easing-10.13.1.tgz";
        sha512 = "INEsInHHDHVgx0dp5qlXi1lMXBqYicgLMMSn3zfGzaIvcaEbI1Uz8BoyNV4BiclTupG7RYIh+T6BU83ZcEe74g==";
      };
    };
    "@motionone/generators-10.13.1" = {
      name = "_at_motionone_slash_generators";
      packageName = "@motionone/generators";
      version = "10.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@motionone/generators/-/generators-10.13.1.tgz";
        sha512 = "+HK5u2YcNJCckTTqfOLgSVcrWv2z1dVwrSZEMVJuAh0EnWEWGDJRvMBoPc0cFf/osbkA2Rq9bH2+vP0Ex/D8uw==";
      };
    };
    "@motionone/types-10.13.0" = {
      name = "_at_motionone_slash_types";
      packageName = "@motionone/types";
      version = "10.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@motionone/types/-/types-10.13.0.tgz";
        sha512 = "qegk4qg8U1N9ZwAJ187BG3TkZz1k9LP/pvNtCSlqdq/PMUDKlCFG4ZnjJ481P0IOH/vIw1OzIbKIuyg0A3rk9g==";
      };
    };
    "@motionone/utils-10.13.1" = {
      name = "_at_motionone_slash_utils";
      packageName = "@motionone/utils";
      version = "10.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@motionone/utils/-/utils-10.13.1.tgz";
        sha512 = "TjDPTIppaf3ofBXQv4ZzAketJgN0sclALXfZ6mfrkjJkOy83mLls9744F+6S+VKCpBmvbZcBY4PQfrfhAfeMtA==";
      };
    };
    "@quri/squiggle-lang-0.2.12" = {
      name = "_at_quri_slash_squiggle-lang";
      packageName = "@quri/squiggle-lang";
      version = "0.2.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@quri/squiggle-lang/-/squiggle-lang-0.2.12.tgz";
        sha512 = "fgv9DLvPlX/TqPSacKSW3GZ5S9H/YwqaMoRdFrn5SJjHnnMh/xJW/9iyzzgOxPCXov9xFeDvL159tkbStMm7vw==";
      };
    };
    "@react-hook/latest-1.0.3" = {
      name = "_at_react-hook_slash_latest";
      packageName = "@react-hook/latest";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@react-hook/latest/-/latest-1.0.3.tgz";
        sha512 = "dy6duzl+JnAZcDbNTfmaP3xHiKtbXYOaz3G51MGVljh548Y8MWzTr+PHLOfvpypEVW9zwvl+VyKjbWKEVbV1Rg==";
      };
    };
    "@react-hook/passive-layout-effect-1.2.1" = {
      name = "_at_react-hook_slash_passive-layout-effect";
      packageName = "@react-hook/passive-layout-effect";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@react-hook/passive-layout-effect/-/passive-layout-effect-1.2.1.tgz";
        sha512 = "IwEphTD75liO8g+6taS+4oqz+nnroocNfWVHWz7j+N+ZO2vYrc6PV1q7GQhuahL0IOR7JccFTsFKQ/mb6iZWAg==";
      };
    };
    "@react-hook/resize-observer-1.2.6" = {
      name = "_at_react-hook_slash_resize-observer";
      packageName = "@react-hook/resize-observer";
      version = "1.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@react-hook/resize-observer/-/resize-observer-1.2.6.tgz";
        sha512 = "DlBXtLSW0DqYYTW3Ft1/GQFZlTdKY5VAFIC4+km6IK5NiPPDFchGbEJm1j6pSgMqPRHbUQgHJX7RaR76ic1LWA==";
      };
    };
    "@react-hook/size-2.1.2" = {
      name = "_at_react-hook_slash_size";
      packageName = "@react-hook/size";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@react-hook/size/-/size-2.1.2.tgz";
        sha512 = "BmE5asyRDxSuQ9p14FUKJ0iBRgV9cROjqNG9jT/EjCM+xHha1HVqbPoT+14FQg1K7xIydabClCibUY4+1tw/iw==";
      };
    };
    "@rescript/std-9.1.4" = {
      name = "_at_rescript_slash_std";
      packageName = "@rescript/std";
      version = "9.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rescript/std/-/std-9.1.4.tgz";
        sha512 = "OHBORysVe6vmyllL24S2sXiwLGrpVRbZW5k2FverbjY3QF81VoyCRYL6kMOSNMEn9GseO/oDubK8+nvVzCSVMA==";
      };
    };
    "@stdlib/array-0.0.12" = {
      name = "_at_stdlib_slash_array";
      packageName = "@stdlib/array";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/array/-/array-0.0.12.tgz";
        sha512 = "nDksiuvRC1dSTHrf5yOGQmlRwAzSKV8MdFQwFSvLbZGGhi5Y4hExqea5HloLgNVouVs8lnAFi2oubSM4Mc7YAg==";
      };
    };
    "@stdlib/assert-0.0.12" = {
      name = "_at_stdlib_slash_assert";
      packageName = "@stdlib/assert";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/assert/-/assert-0.0.12.tgz";
        sha512 = "38FxFf+ZoQZbdc+m09UsWtaCmzd/2e7im0JOaaFYE7icmRfm+4KiE9BRvBT4tIn7ioLB2f9PsBicKjIsf+tY1w==";
      };
    };
    "@stdlib/bigint-0.0.11" = {
      name = "_at_stdlib_slash_bigint";
      packageName = "@stdlib/bigint";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/bigint/-/bigint-0.0.11.tgz";
        sha512 = "uz0aYDLABAYyqxaCSHYbUt0yPkXYUCR7TrVvHN+UUD3i8FZ02ZKcLO+faKisDyxKEoSFTNtn3Ro8Ir5ebOlVXQ==";
      };
    };
    "@stdlib/blas-0.0.12" = {
      name = "_at_stdlib_slash_blas";
      packageName = "@stdlib/blas";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/blas/-/blas-0.0.12.tgz";
        sha512 = "nWY749bWceuoWQ7gz977blCwR7lyQ/rsIXVO4b600h+NFpeA2i/ea7MYC680utIbeu2cnDWHdglBPoK535VAzA==";
      };
    };
    "@stdlib/buffer-0.0.11" = {
      name = "_at_stdlib_slash_buffer";
      packageName = "@stdlib/buffer";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/buffer/-/buffer-0.0.11.tgz";
        sha512 = "Jeie5eDDa1tVuRcuU+cBXI/oOXSmMxUUccZpqXzgYe0IO8QSNtNxv9mUTzJk/m5wH+lmLoDvNxzPpOH9TODjJg==";
      };
    };
    "@stdlib/cli-0.0.10" = {
      name = "_at_stdlib_slash_cli";
      packageName = "@stdlib/cli";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/cli/-/cli-0.0.10.tgz";
        sha512 = "OITGaxG46kwK799+NuOd/+ccosJ9koVuQBC610DDJv0ZJf8mD7sbjGXrmue9C4EOh8MP7Vm/6HN14BojX8oTCg==";
      };
    };
    "@stdlib/complex-0.0.12" = {
      name = "_at_stdlib_slash_complex";
      packageName = "@stdlib/complex";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/complex/-/complex-0.0.12.tgz";
        sha512 = "UbZBdaUxT2G+lsTIrVlRZwx2IRY6GXnVILggeejsIVxHSuK+oTyapfetcAv0FJFLP+Rrr+ZzrN4b9G3hBw6NHA==";
      };
    };
    "@stdlib/constants-0.0.11" = {
      name = "_at_stdlib_slash_constants";
      packageName = "@stdlib/constants";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/constants/-/constants-0.0.11.tgz";
        sha512 = "cWKy0L9hXHUQTvFzdPkTvZnn/5Pjv7H4UwY0WC1rLt+A5CxFDJKjvnIi9ypSzJS3CAiGl1ZaHCdadoqXhNdkUg==";
      };
    };
    "@stdlib/fs-0.0.12" = {
      name = "_at_stdlib_slash_fs";
      packageName = "@stdlib/fs";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/fs/-/fs-0.0.12.tgz";
        sha512 = "zcDLbt39EEM3M3wJW6luChS53B8T+TMJkjs2526UpKJ71O0/0adR57cI7PfCpkMd33d05uM7GM+leEj4eks4Cw==";
      };
    };
    "@stdlib/math-0.0.11" = {
      name = "_at_stdlib_slash_math";
      packageName = "@stdlib/math";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/math/-/math-0.0.11.tgz";
        sha512 = "qI78sR1QqGjHj8k/aAqkZ51Su2fyBvaR/jMKQqcB/ML8bpYpf+QGlGvTty5Qdru/wpqds4kVFOVbWGcNFIV2+Q==";
      };
    };
    "@stdlib/ndarray-0.0.13" = {
      name = "_at_stdlib_slash_ndarray";
      packageName = "@stdlib/ndarray";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/ndarray/-/ndarray-0.0.13.tgz";
        sha512 = "Z+U9KJP4U2HWrLtuAXSPvhNetAdqaNLMcliR6S/fz+VPlFDeymRK7omRFMgVQ+1zcAvIgKZGJxpLC3vjiPUYEw==";
      };
    };
    "@stdlib/nlp-0.0.11" = {
      name = "_at_stdlib_slash_nlp";
      packageName = "@stdlib/nlp";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/nlp/-/nlp-0.0.11.tgz";
        sha512 = "D9avYWANm0Db2W7RpzdSdi5GxRYALGAqUrNnRnnKIO6sMEfr/DvONoAbWruda4QyvSC+0MJNwcEn7+PHhRwYhw==";
      };
    };
    "@stdlib/number-0.0.10" = {
      name = "_at_stdlib_slash_number";
      packageName = "@stdlib/number";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/number/-/number-0.0.10.tgz";
        sha512 = "RyfoP9MlnX4kccvg8qv7vYQPbLdzfS1Mnp/prGOoWhvMG3pyBwFAan34kwFb5IS/zHC3W5EmrgXCV2QWyLg/Kg==";
      };
    };
    "@stdlib/os-0.0.12" = {
      name = "_at_stdlib_slash_os";
      packageName = "@stdlib/os";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/os/-/os-0.0.12.tgz";
        sha512 = "O7lklZ/9XEzoCmYvzjPh7jrFWkbpOSHGI71ve3dkSvBy5tyiSL3TtivfKsIC+9ZxuEJZ3d3lIjc9e+yz4HVbqQ==";
      };
    };
    "@stdlib/process-0.0.12" = {
      name = "_at_stdlib_slash_process";
      packageName = "@stdlib/process";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/process/-/process-0.0.12.tgz";
        sha512 = "P0X0TMvkissBE1Wr877Avi2/AxmP7X5Toa6GatHbpJdDg6jQmN4SgPd+NZNp98YtZUyk478c8XSIzMr1krQ20g==";
      };
    };
    "@stdlib/random-0.0.12" = {
      name = "_at_stdlib_slash_random";
      packageName = "@stdlib/random";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/random/-/random-0.0.12.tgz";
        sha512 = "c5yND4Ahnm9Jx0I+jsKhn4Yrz10D53ALSrIe3PG1qIz3kNFcIPnmvCuNGd+3V4ch4Mbrez55Y8z/ZC5RJh4vJQ==";
      };
    };
    "@stdlib/regexp-0.0.13" = {
      name = "_at_stdlib_slash_regexp";
      packageName = "@stdlib/regexp";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/regexp/-/regexp-0.0.13.tgz";
        sha512 = "3JT5ZIoq/1nXY+dY+QtkU8/m7oWDeekyItEEXMx9c/AOf0ph8fmvTUGMDNfUq0RetcznFe3b66kFz6Zt4XHviA==";
      };
    };
    "@stdlib/stats-0.0.13" = {
      name = "_at_stdlib_slash_stats";
      packageName = "@stdlib/stats";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/stats/-/stats-0.0.13.tgz";
        sha512 = "hm+t32dKbx/L7+7WlQ1o4NDEzV0J4QSnwFBCsIMIAO8+VPxTZ4FxyNERl4oKlS3hZZe4AVKjoOVhBDtgEWrS4g==";
      };
    };
    "@stdlib/streams-0.0.12" = {
      name = "_at_stdlib_slash_streams";
      packageName = "@stdlib/streams";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/streams/-/streams-0.0.12.tgz";
        sha512 = "YLUlXwjJNknHp92IkJUdvn5jEQjDckpawKhDLLCoxyh3h5V+w/8+61SH7TMTfKx5lBxKJ8vvtchZh90mIJOAjQ==";
      };
    };
    "@stdlib/strided-0.0.12" = {
      name = "_at_stdlib_slash_strided";
      packageName = "@stdlib/strided";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/strided/-/strided-0.0.12.tgz";
        sha512 = "1NINP+Y7IJht34iri/bYLY7TVxrip51f6Z3qWxGHUCH33kvk5H5QqV+RsmFEGbbyoGtdeHrT2O+xA+7R2e3SNg==";
      };
    };
    "@stdlib/string-0.0.14" = {
      name = "_at_stdlib_slash_string";
      packageName = "@stdlib/string";
      version = "0.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/string/-/string-0.0.14.tgz";
        sha512 = "1ClvUTPysens7GZz3WsrkFYIFs8qDmnXkyAd3zMvTXgRpy7hqrv6nNzLMQj8BHv5cBWaWPOXYd/cZ+JyMnZNQQ==";
      };
    };
    "@stdlib/symbol-0.0.12" = {
      name = "_at_stdlib_slash_symbol";
      packageName = "@stdlib/symbol";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/symbol/-/symbol-0.0.12.tgz";
        sha512 = "2IDhpzWVGeLHgsvIsX12RXvf78r7xBkc4QLoRUv3k7Cp61BisR1Ym1p0Tq9PbxT8fknlvLToh9n5RpmESi2d4w==";
      };
    };
    "@stdlib/time-0.0.14" = {
      name = "_at_stdlib_slash_time";
      packageName = "@stdlib/time";
      version = "0.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/time/-/time-0.0.14.tgz";
        sha512 = "1gMFCQTabMVIgww+k4g8HHHIhyy1tIlvwT8mC0BHW7Q7TzDAgobwL0bvor+lwvCb5LlDAvNQEpaRgVT99QWGeQ==";
      };
    };
    "@stdlib/types-0.0.14" = {
      name = "_at_stdlib_slash_types";
      packageName = "@stdlib/types";
      version = "0.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/types/-/types-0.0.14.tgz";
        sha512 = "AP3EI9/il/xkwUazcoY+SbjtxHRrheXgSbWZdEGD+rWpEgj6n2i63hp6hTOpAB5NipE0tJwinQlDGOuQ1lCaCw==";
      };
    };
    "@stdlib/utils-0.0.12" = {
      name = "_at_stdlib_slash_utils";
      packageName = "@stdlib/utils";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/utils/-/utils-0.0.12.tgz";
        sha512 = "+JhFpl6l7RSq/xGnbWRQ5dAL90h9ONj8MViqlb7teBZFtePZLMwoRA1wssypFcJ8SFMRWQn7lPmpYVUkGwRSOg==";
      };
    };
    "@types/clone-2.1.1" = {
      name = "_at_types_slash_clone";
      packageName = "@types/clone";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/clone/-/clone-2.1.1.tgz";
        sha512 = "BZIU34bSYye0j/BFcPraiDZ5ka6MJADjcDVELGf7glr9K+iE8NYVjFslJFVWzskSxkLLyCrSPScE82/UUoBSvg==";
      };
    };
    "@types/estree-0.0.50" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "0.0.50";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-0.0.50.tgz";
        sha512 = "C6N5s2ZFtuZRj54k2/zyRhNDjJwwcViAM3Nbm8zjBpbqAdZ00mr0CFxvSKeO8Y/e03WVFLpQMdHYVfUd6SB+Hw==";
      };
    };
    "@types/js-cookie-2.2.7" = {
      name = "_at_types_slash_js-cookie";
      packageName = "@types/js-cookie";
      version = "2.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/js-cookie/-/js-cookie-2.2.7.tgz";
        sha512 = "aLkWa0C0vO5b4Sr798E26QgOkss68Un0bLjs7u9qxzPT5CG+8DuNTffWES58YzJs3hrVAOs1wonycqEBqNJubA==";
      };
    };
    "@types/lodash-4.14.182" = {
      name = "_at_types_slash_lodash";
      packageName = "@types/lodash";
      version = "4.14.182";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/lodash/-/lodash-4.14.182.tgz";
        sha512 = "/THyiqyQAP9AfARo4pF+aCGcyiQ94tX/Is2I7HofNRqoYLgN1PBoOWu2/zTA5zMxzP5EFutMtWtGAFRKUe961Q==";
      };
    };
    "@types/prop-types-15.7.5" = {
      name = "_at_types_slash_prop-types";
      packageName = "@types/prop-types";
      version = "15.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/prop-types/-/prop-types-15.7.5.tgz";
        sha512 = "JCB8C6SnDoQf0cNycqd/35A7MjcnK+ZTqE7judS6o7utxUCg6imJg3QK2qzHKszlTjcj2cn+NwMB2i96ubpj7w==";
      };
    };
    "@types/react-18.0.15" = {
      name = "_at_types_slash_react";
      packageName = "@types/react";
      version = "18.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react/-/react-18.0.15.tgz";
        sha512 = "iz3BtLuIYH1uWdsv6wXYdhozhqj20oD4/Hk2DNXIn1kFsmp9x8d9QB6FnPhfkbhd2PgEONt9Q1x/ebkwjfFLow==";
      };
    };
    "@types/scheduler-0.16.2" = {
      name = "_at_types_slash_scheduler";
      packageName = "@types/scheduler";
      version = "0.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/scheduler/-/scheduler-0.16.2.tgz";
        sha512 = "hppQEBDmlwhFAXKJX2KnWLYu5yMfi91yazPb2l+lbJiwW+wdo1gNeRA+3RgNSO39WYX2euey41KEwnqesU2Jew==";
      };
    };
    "@xobotyi/scrollbar-width-1.9.5" = {
      name = "_at_xobotyi_slash_scrollbar-width";
      packageName = "@xobotyi/scrollbar-width";
      version = "1.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xobotyi/scrollbar-width/-/scrollbar-width-1.9.5.tgz";
        sha512 = "N8tkAACJx2ww8vFMneJmaAgmjAG1tnVBZJRLRcx061tmsLRZHSEZSLuGWnwPtunsSLvSqXQ2wfp7Mgqg1I+2dQ==";
      };
    };
    "ace-builds-1.8.1" = {
      name = "ace-builds";
      packageName = "ace-builds";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ace-builds/-/ace-builds-1.8.1.tgz";
        sha512 = "wjEQ4khMQYg9FfdEDoOtqdoHwcwFL48H0VB3te5b5A3eqHwxsTw8IX6+xzfisgborIb8dYU+1y9tcmtGFrCPIg==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "aria-hidden-1.1.3" = {
      name = "aria-hidden";
      packageName = "aria-hidden";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/aria-hidden/-/aria-hidden-1.1.3.tgz";
        sha512 = "RhVWFtKH5BiGMycI72q2RAFMLQi8JP9bLuQXgR5a8Znp7P5KOIADSJeyfI8PCVxLEp067B2HbP5JIiI/PXIZeA==";
      };
    };
    "array-flat-polyfill-1.0.1" = {
      name = "array-flat-polyfill";
      packageName = "array-flat-polyfill";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flat-polyfill/-/array-flat-polyfill-1.0.1.tgz";
        sha512 = "hfJmKupmQN0lwi0xG6FQ5U8Rd97RnIERplymOv/qpq8AoNKPPAnxJadjFA23FNWm88wykh9HmpLJUUwUtNU/iw==";
      };
    };
    "cliui-7.0.4" = {
      name = "cliui";
      packageName = "cliui";
      version = "7.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-7.0.4.tgz";
        sha512 = "OcRE68cOsVMXp1Yvonl/fzkQOyjLSu/8bhPDfQt0e0/Eb283TKP20Fs2MqoPsr9SwA595rRCA+QMzYc9nBP+JQ==";
      };
    };
    "clone-2.1.2" = {
      name = "clone";
      packageName = "clone";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-2.1.2.tgz";
        sha512 = "3Pe/CF1Nn94hyhIYpjtiLhdCoEoz0DqQ+988E9gmeEdQZlojxnOb74wctFyuwWQHzqyf9X7C7MG8juUpqBJT8w==";
      };
    };
    "clsx-1.2.1" = {
      name = "clsx";
      packageName = "clsx";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clsx/-/clsx-1.2.1.tgz";
        sha512 = "EcR6r5a8bj6pu3ycsa/E/cKVGuTgZJZdsyUYHOksG/UHIiKfjxzRxYJpyVBwYaQeOvghal9fcc4PidlgzugAQg==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "commander-7.2.0" = {
      name = "commander";
      packageName = "commander";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-7.2.0.tgz";
        sha512 = "QrWXB+ZQSVPmIWIhtEO9H+gwHaMGYiF5ChvoJ+K9ZGHG/sVsa6yiesAD1GC/x46sET00Xlwo1u49RVVVzvcSkw==";
      };
    };
    "complex.js-2.1.1" = {
      name = "complex.js";
      packageName = "complex.js";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/complex.js/-/complex.js-2.1.1.tgz";
        sha512 = "8njCHOTtFFLtegk6zQo0kkVX1rngygb/KQI6z1qZxlFI3scluC+LVTCFbrkWjBv4vvLlbQ9t88IPMC6k95VTTg==";
      };
    };
    "copy-to-clipboard-3.3.1" = {
      name = "copy-to-clipboard";
      packageName = "copy-to-clipboard";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/copy-to-clipboard/-/copy-to-clipboard-3.3.1.tgz";
        sha512 = "i13qo6kIHTTpCm8/Wup+0b1mVWETvu2kIMzKoK8FpkLkFxlt0znUAHcMzox+T8sPlqtZXq3CulEjQHsYiGFJUw==";
      };
    };
    "core-util-is-1.0.3" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.3.tgz";
        sha512 = "ZQBvi1DcpJ4GDqanjucZ2Hj3wEO5pZDS89BWbkcrvdxksJorwUDDZamX9ldFkp9aw2lmBDLgkObEA4DWNJ9FYQ==";
      };
    };
    "css-in-js-utils-2.0.1" = {
      name = "css-in-js-utils";
      packageName = "css-in-js-utils";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-in-js-utils/-/css-in-js-utils-2.0.1.tgz";
        sha512 = "PJF0SpJT+WdbVVt0AOYp9C8GnuruRlL/UFW7932nLWmFLQTaWEzTBQEx7/hn4BuV+WON75iAViSUJLiU3PKbpA==";
      };
    };
    "css-tree-1.1.3" = {
      name = "css-tree";
      packageName = "css-tree";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-tree/-/css-tree-1.1.3.tgz";
        sha512 = "tRpdppF7TRazZrjJ6v3stzv93qxRcSsFmW6cX0Zm2NVKpxE1WV1HblnghVv9TreireHkqI/VDEsfolRF1p6y7Q==";
      };
    };
    "csstype-3.1.0" = {
      name = "csstype";
      packageName = "csstype";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-3.1.0.tgz";
        sha512 = "uX1KG+x9h5hIJsaKR9xHUeUraxf8IODOwq9JLNPq6BwB04a/xgpq3rcx47l5BZu5zBPlgD342tdke3Hom/nJRA==";
      };
    };
    "d3-array-3.1.1" = {
      name = "d3-array";
      packageName = "d3-array";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-array/-/d3-array-3.1.1.tgz";
        sha512 = "33qQ+ZoZlli19IFiQx4QEpf2CBEayMRzhlisJHSCsSUbDXv6ZishqS1x7uFVClKG4Wr7rZVHvaAttoLow6GqdQ==";
      };
    };
    "d3-array-3.2.0" = {
      name = "d3-array";
      packageName = "d3-array";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-array/-/d3-array-3.2.0.tgz";
        sha512 = "3yXFQo0oG3QCxbF06rMPFyGRMGJNS7NvsV1+2joOjbBE+9xvWQ8+GcMJAjRCzw06zQ3/arXeJgbPYcjUCuC+3g==";
      };
    };
    "d3-color-3.1.0" = {
      name = "d3-color";
      packageName = "d3-color";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-color/-/d3-color-3.1.0.tgz";
        sha512 = "zg/chbXyeBtMQ1LbD/WSoW2DpC3I0mpmPdW+ynRTj/x2DAWYrIY7qeZIHidozwV24m4iavr15lNwIwLxRmOxhA==";
      };
    };
    "d3-delaunay-6.0.2" = {
      name = "d3-delaunay";
      packageName = "d3-delaunay";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-delaunay/-/d3-delaunay-6.0.2.tgz";
        sha512 = "IMLNldruDQScrcfT+MWnazhHbDJhcRJyOEBAJfwQnHle1RPh6WDuLvxNArUju2VSMSUuKlY5BGHRJ2cYyoFLQQ==";
      };
    };
    "d3-dispatch-3.0.1" = {
      name = "d3-dispatch";
      packageName = "d3-dispatch";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-dispatch/-/d3-dispatch-3.0.1.tgz";
        sha512 = "rzUyPU/S7rwUflMyLc1ETDeBj0NRuHKKAcvukozwhshr6g6c5d8zh4c2gQjY2bZ0dXeGLWc1PF174P2tVvKhfg==";
      };
    };
    "d3-dsv-3.0.1" = {
      name = "d3-dsv";
      packageName = "d3-dsv";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-dsv/-/d3-dsv-3.0.1.tgz";
        sha512 = "UG6OvdI5afDIFP9w4G0mNq50dSOsXHJaRE8arAS5o9ApWnIElp8GZw1Dun8vP8OyHOZ/QJUKUJwxiiCCnUwm+Q==";
      };
    };
    "d3-force-3.0.0" = {
      name = "d3-force";
      packageName = "d3-force";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-force/-/d3-force-3.0.0.tgz";
        sha512 = "zxV/SsA+U4yte8051P4ECydjD/S+qeYtnaIyAs9tgHCqfguma/aAQDjo85A9Z6EKhBirHRJHXIgJUlffT4wdLg==";
      };
    };
    "d3-format-3.1.0" = {
      name = "d3-format";
      packageName = "d3-format";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-format/-/d3-format-3.1.0.tgz";
        sha512 = "YyUI6AEuY/Wpt8KWLgZHsIU86atmikuoOmCfommt0LYHiQSPjvX2AcFc38PX0CBpr2RCyZhjex+NS/LPOv6YqA==";
      };
    };
    "d3-geo-3.0.1" = {
      name = "d3-geo";
      packageName = "d3-geo";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-geo/-/d3-geo-3.0.1.tgz";
        sha512 = "Wt23xBych5tSy9IYAM1FR2rWIBFWa52B/oF/GYe5zbdHrg08FU8+BuI6X4PvTwPDdqdAdq04fuWJpELtsaEjeA==";
      };
    };
    "d3-geo-projection-4.0.0" = {
      name = "d3-geo-projection";
      packageName = "d3-geo-projection";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-geo-projection/-/d3-geo-projection-4.0.0.tgz";
        sha512 = "p0bK60CEzph1iqmnxut7d/1kyTmm3UWtPlwdkM31AU+LW+BXazd5zJdoCn7VFxNCHXRngPHRnsNn5uGjLRGndg==";
      };
    };
    "d3-hierarchy-3.1.2" = {
      name = "d3-hierarchy";
      packageName = "d3-hierarchy";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-hierarchy/-/d3-hierarchy-3.1.2.tgz";
        sha512 = "FX/9frcub54beBdugHjDCdikxThEqjnR93Qt7PvQTOHxyiNCAlvMrHhclk3cD5VeAaq9fxmfRp+CnWw9rEMBuA==";
      };
    };
    "d3-interpolate-3.0.1" = {
      name = "d3-interpolate";
      packageName = "d3-interpolate";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-interpolate/-/d3-interpolate-3.0.1.tgz";
        sha512 = "3bYs1rOD33uo8aqJfKP3JWPAibgw8Zm2+L9vBKEHJ2Rg+viTR7o5Mmv5mZcieN+FRYaAOWX5SJATX6k1PWz72g==";
      };
    };
    "d3-path-3.0.1" = {
      name = "d3-path";
      packageName = "d3-path";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-path/-/d3-path-3.0.1.tgz";
        sha512 = "gq6gZom9AFZby0YLduxT1qmrp4xpBA1YZr19OI717WIdKE2OM5ETq5qrHLb301IgxhLwcuxvGZVLeeWc/k1I6w==";
      };
    };
    "d3-quadtree-3.0.1" = {
      name = "d3-quadtree";
      packageName = "d3-quadtree";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-quadtree/-/d3-quadtree-3.0.1.tgz";
        sha512 = "04xDrxQTDTCFwP5H6hRhsRcb9xxv2RzkcsygFzmkSIOJy3PeRJP7sNk3VRIbKXcog561P9oU0/rVH6vDROAgUw==";
      };
    };
    "d3-scale-4.0.2" = {
      name = "d3-scale";
      packageName = "d3-scale";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-scale/-/d3-scale-4.0.2.tgz";
        sha512 = "GZW464g1SH7ag3Y7hXjf8RoUuAFIqklOAq3MRl4OaWabTFJY9PN/E1YklhXLh+OQ3fM9yS2nOkCoS+WLZ6kvxQ==";
      };
    };
    "d3-shape-3.1.0" = {
      name = "d3-shape";
      packageName = "d3-shape";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-shape/-/d3-shape-3.1.0.tgz";
        sha512 = "tGDh1Muf8kWjEDT/LswZJ8WF85yDZLvVJpYU9Nq+8+yW1Z5enxrmXOhTArlkaElU+CTn0OTVNli+/i+HP45QEQ==";
      };
    };
    "d3-time-3.0.0" = {
      name = "d3-time";
      packageName = "d3-time";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-time/-/d3-time-3.0.0.tgz";
        sha512 = "zmV3lRnlaLI08y9IMRXSDshQb5Nj77smnfpnd2LrBa/2K281Jijactokeak14QacHs/kKq0AQ121nidNYlarbQ==";
      };
    };
    "d3-time-format-4.1.0" = {
      name = "d3-time-format";
      packageName = "d3-time-format";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-time-format/-/d3-time-format-4.1.0.tgz";
        sha512 = "dJxPBlzC7NugB2PDLwo9Q8JiTR3M3e4/XANkreKSUxF8vvXKqm1Yfq4Q5dl8budlunRVlUUaDUgFt7eA8D6NLg==";
      };
    };
    "d3-timer-3.0.1" = {
      name = "d3-timer";
      packageName = "d3-timer";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-timer/-/d3-timer-3.0.1.tgz";
        sha512 = "ndfJ/JxxMd3nw31uyKoY2naivF+r29V+Lc0svZxe1JvvIRmi8hUsrMvdOwgS1o6uBHmiz91geQ0ylPP0aj1VUA==";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "decimal.js-10.3.1" = {
      name = "decimal.js";
      packageName = "decimal.js";
      version = "10.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/decimal.js/-/decimal.js-10.3.1.tgz";
        sha512 = "V0pfhfr8suzyPGOx3nmq4aHqabehUZn6Ch9kyFpV79TGDTWFmHqUqXdabR7QHqxzrYolF4+tVmJhUG4OURg5dQ==";
      };
    };
    "delaunator-5.0.0" = {
      name = "delaunator";
      packageName = "delaunator";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delaunator/-/delaunator-5.0.0.tgz";
        sha512 = "AyLvtyJdbv/U1GkiS6gUUzclRoAY4Gs75qkMygJJhU75LW4DNuSF2RMzpxs9jw9Oz1BobHjTdkG3zdP55VxAqw==";
      };
    };
    "diff-match-patch-1.0.5" = {
      name = "diff-match-patch";
      packageName = "diff-match-patch";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/diff-match-patch/-/diff-match-patch-1.0.5.tgz";
        sha512 = "IayShXAgj/QMXgB0IWmKx+rOPuGMhqm5w6jvFxmVenXKIzRqTAAsbBPT3kWQeGANj3jGgvcvv4yK6SxqYmikgw==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "error-stack-parser-2.1.4" = {
      name = "error-stack-parser";
      packageName = "error-stack-parser";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-stack-parser/-/error-stack-parser-2.1.4.tgz";
        sha512 = "Sk5V6wVazPhq5MhpO+AUxJn5x7XSXGl1R93Vn7i+zS15KDVxQijejNCrz8340/2bgLBjR9GtEG8ZVKONDjcqGQ==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "escape-latex-1.2.0" = {
      name = "escape-latex";
      packageName = "escape-latex";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-latex/-/escape-latex-1.2.0.tgz";
        sha512 = "nV5aVWW1K0wEiUIEdZ4erkGGH8mDxGyxSeqPzRNtWP7ataw+/olFObw7hujFWlVjNsaDFw5VZ5NzVSIqRgfTiw==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-json-patch-3.1.1" = {
      name = "fast-json-patch";
      packageName = "fast-json-patch";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-patch/-/fast-json-patch-3.1.1.tgz";
        sha512 = "vf6IHUX2SBcA+5/+4883dsIjpBTqmfBjmYiWK1savxQmFk4JfBMLa7ynTYOs1Rolp/T1betJxHiGD3g1Mn8lUQ==";
      };
    };
    "fast-json-stable-stringify-2.1.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
        sha512 = "lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
      };
    };
    "fast-shallow-equal-1.0.0" = {
      name = "fast-shallow-equal";
      packageName = "fast-shallow-equal";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-shallow-equal/-/fast-shallow-equal-1.0.0.tgz";
        sha512 = "HPtaa38cPgWvaCFmRNhlc6NG7pv6NUHqjPgVAkWGoB9mQMwYB27/K0CvOM5Czy+qpT3e8XJ6Q4aPAnzpNpzNaw==";
      };
    };
    "fastest-stable-stringify-2.0.2" = {
      name = "fastest-stable-stringify";
      packageName = "fastest-stable-stringify";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastest-stable-stringify/-/fastest-stable-stringify-2.0.2.tgz";
        sha512 = "bijHueCGd0LqqNK9b5oCMHc0MluJAx0cwqASgbWMvkO01lCYgIhacVRLcaDz3QnyYIRNJRDwMb41VuT6pHJ91Q==";
      };
    };
    "fraction.js-4.2.0" = {
      name = "fraction.js";
      packageName = "fraction.js";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fraction.js/-/fraction.js-4.2.0.tgz";
        sha512 = "MhLuK+2gUcnZe8ZHlaaINnQLl0xRIGRfcGk2yl8xoQAfHrSsL3rYu6FCmBdkdbhc9EPlwyGHewaRsvwRMJtAlA==";
      };
    };
    "framer-motion-6.5.1" = {
      name = "framer-motion";
      packageName = "framer-motion";
      version = "6.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/framer-motion/-/framer-motion-6.5.1.tgz";
        sha512 = "o1BGqqposwi7cgDrtg0dNONhkmPsUFDaLcKXigzuTFC5x58mE8iyTazxSudFzmT6MEyJKfjjU8ItoMe3W+3fiw==";
      };
    };
    "framesync-6.0.1" = {
      name = "framesync";
      packageName = "framesync";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/framesync/-/framesync-6.0.1.tgz";
        sha512 = "fUY88kXvGiIItgNC7wcTOl0SNRCVXMKSWW2Yzfmn7EKNc+MpCzcz9DhdHcdjbrtN3c6R4H5dTY2jiCpPdysEjA==";
      };
    };
    "get-caller-file-2.0.5" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz";
        sha512 = "DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==";
      };
    };
    "hey-listen-1.0.8" = {
      name = "hey-listen";
      packageName = "hey-listen";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/hey-listen/-/hey-listen-1.0.8.tgz";
        sha512 = "COpmrF2NOg4TBWUJ5UVyaCU2A88wEMkUPK4hNqyCkqHbxT92BbvfjoSozkAIIm6XhicGlJHhFdullInrdhwU8Q==";
      };
    };
    "hyphenate-style-name-1.0.4" = {
      name = "hyphenate-style-name";
      packageName = "hyphenate-style-name";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/hyphenate-style-name/-/hyphenate-style-name-1.0.4.tgz";
        sha512 = "ygGZLjmXfPHj+ZWh6LwbC37l43MhfztxetbFCoYTM2VjkIUpeHgSNn7QIyVFj7YQ1Wl9Cbw5sholVJPzWvC2MQ==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "inline-style-prefixer-6.0.1" = {
      name = "inline-style-prefixer";
      packageName = "inline-style-prefixer";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inline-style-prefixer/-/inline-style-prefixer-6.0.1.tgz";
        sha512 = "AsqazZ8KcRzJ9YPN1wMH2aNM7lkWQ8tSPrW5uDk1ziYwiAPWSZnUsC7lfZq+BDqLqz0B4Pho5wscWcJzVvRzDQ==";
      };
    };
    "internmap-2.0.3" = {
      name = "internmap";
      packageName = "internmap";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/internmap/-/internmap-2.0.3.tgz";
        sha512 = "5Hh7Y1wQbvY5ooGgPbDaL5iYLAPzMTUrjMulskHLH6wnv/A+1q5rgEaiuqEjB+oxGXIVZs1FF+R/KPN3ZSQYYg==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha512 = "VLghIWNM6ELQzo7zwmcg0NmTVyWKYjvIeM83yjp0wRDTmUnrM678fQbcKBo6n2CJEF0szoG//ytg+TKla89ALQ==";
      };
    };
    "isobject-3.0.1" = {
      name = "isobject";
      packageName = "isobject";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-3.0.1.tgz";
        sha512 = "WhB9zCku7EGTj/HQQRz5aUQEUeoQZH2bWcltRErOpymJ4boYE6wL9Tbr23krRPSZ+C5zqNSrSw+Cc7sZZ4b7vg==";
      };
    };
    "javascript-natural-sort-0.7.1" = {
      name = "javascript-natural-sort";
      packageName = "javascript-natural-sort";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/javascript-natural-sort/-/javascript-natural-sort-0.7.1.tgz";
        sha512 = "nO6jcEfZWQXDhOiBtG2KvKyEptz7RVbpGP4vTD2hLBdmNQSsCiicO2Ioinv6UI4y9ukqnBpy+XZ9H6uLNgJTlw==";
      };
    };
    "js-cookie-2.2.1" = {
      name = "js-cookie";
      packageName = "js-cookie";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-cookie/-/js-cookie-2.2.1.tgz";
        sha512 = "HvdH2LzI/EAZcUwA8+0nKNtWHqS+ZmijLA30RwZA0bo7ToCckjK5MkGhjED9KoRcXO6BaGI3I9UIzSA1FKFPOQ==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "json-stringify-pretty-compact-3.0.0" = {
      name = "json-stringify-pretty-compact";
      packageName = "json-stringify-pretty-compact";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-pretty-compact/-/json-stringify-pretty-compact-3.0.0.tgz";
        sha512 = "Rc2suX5meI0S3bfdZuA7JMFBGkJ875ApfVyq2WHELjBiiG22My/l7/8zPpH/CfFVQHuVLd8NLR0nv6vi0BYYKA==";
      };
    };
    "jstat-1.9.5" = {
      name = "jstat";
      packageName = "jstat";
      version = "1.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/jstat/-/jstat-1.9.5.tgz";
        sha512 = "cWnp4vObF5GmB2XsIEzxI/1ZTcYlcfNqxQ/9Fp5KFUa0Jf/4tO0ZkGVnqoEHDisJvYgvn5n3eWZbd2xTVJJPUQ==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lodash-es-4.17.21" = {
      name = "lodash-es";
      packageName = "lodash-es";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash-es/-/lodash-es-4.17.21.tgz";
        sha512 = "mKnC+QJ9pWVzv+C4/U3rRsHapFfHvQFoFB92e52xeyGMcX6/OlIl78je1u8vePzYZSkkogMPJ2yjxxsb89cxyw==";
      };
    };
    "lodash.get-4.4.2" = {
      name = "lodash.get";
      packageName = "lodash.get";
      version = "4.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.get/-/lodash.get-4.4.2.tgz";
        sha512 = "z+Uw/vLuy6gQe8cfaFWD7p0wVv8fJl3mbzXh33RS+0oW2wvUqiRXiQ69gLWSLpgB5/6sU+r6BlQR0MBILadqTQ==";
      };
    };
    "lodash.isequal-4.5.0" = {
      name = "lodash.isequal";
      packageName = "lodash.isequal";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isequal/-/lodash.isequal-4.5.0.tgz";
        sha512 = "pDo3lu8Jhfjqls6GkMgpahsF9kCyayhgykjyLMNFTKWrpVdAQtYyB4muAMWozBB4ig/dtWAmsMxLEI8wuz+DYQ==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "mathjs-11.0.1" = {
      name = "mathjs";
      packageName = "mathjs";
      version = "11.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mathjs/-/mathjs-11.0.1.tgz";
        sha512 = "Kgm+GcTxwD68zupr7BPK0yrlWpTh2q8sMH6VcBcQe5+JCBqcwOrBxBF11WPah7hVv0NCLDnJnFTiXtik1Phasg==";
      };
    };
    "mdn-data-2.0.14" = {
      name = "mdn-data";
      packageName = "mdn-data";
      version = "2.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.14.tgz";
        sha512 = "dn6wd0uw5GsdswPFfsgMp5NSB0/aDe6fK94YJV/AJDYXL6HVLWBsxeq7js7Ad+mU2K9LAlwpk6kN2D5mwCPVow==";
      };
    };
    "minimist-1.2.6" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.6.tgz";
        sha512 = "Jsjnk4bw3YJqYzbdyBiNsPWHPfO++UGG749Cxs6peCu5Xg4nrena6OVxOYxrQTqww0Jmwt+Ref8rggumkTLz9Q==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha512 = "Tpp60P6IUJDTuOq/5Z8cdskzJujfwqfOTkrwIwj7IRISpnkJnT6SyJ4PCPnGMoFjC9ddhal5KVIYtAt97ix05A==";
      };
    };
    "nano-css-5.3.5" = {
      name = "nano-css";
      packageName = "nano-css";
      version = "5.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/nano-css/-/nano-css-5.3.5.tgz";
        sha512 = "vSB9X12bbNu4ALBu7nigJgRViZ6ja3OU7CeuiV1zMIbXOdmkLahgtPmh3GBOlDxbKY0CitqlPdOReGlBLSp+yg==";
      };
    };
    "nanoclone-0.2.1" = {
      name = "nanoclone";
      packageName = "nanoclone";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoclone/-/nanoclone-0.2.1.tgz";
        sha512 = "wynEP02LmIbLpcYw8uBKpcfF6dmg2vcpKqxeH5UcoKEYdExslsdUA4ugFauuaeYdTB76ez6gJW8XAZ6CgkXYxA==";
      };
    };
    "node-fetch-2.6.7" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.7.tgz";
        sha512 = "ZjMPFEfVx5j+y2yF35Kzx5sF7kDzxuDj6ziH4FFbOp87zKDZNx8yExJIb05OGF4Nlt9IHFIMBkRl41VdvcNdbQ==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "pdfast-0.2.0" = {
      name = "pdfast";
      packageName = "pdfast";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pdfast/-/pdfast-0.2.0.tgz";
        sha512 = "cq6TTu6qKSFUHwEahi68k/kqN2mfepjkGrG9Un70cgdRRKLKY6Rf8P8uvP2NvZktaQZNF3YE7agEkLj0vGK9bA==";
      };
    };
    "popmotion-11.0.3" = {
      name = "popmotion";
      packageName = "popmotion";
      version = "11.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/popmotion/-/popmotion-11.0.3.tgz";
        sha512 = "Y55FLdj3UxkR7Vl3s7Qr4e9m0onSnP8W7d/xQLsoJM40vs6UKHFdygs6SWryasTZYqugMjm3BepCF4CWXDiHgA==";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "prop-types-15.8.1" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.8.1.tgz";
        sha512 = "oj87CgZICdulUohogVAR7AjlC0327U4el4L6eAvOqCeudMDVU0NThNaV+b9Df4dXgSP1gXMTnPdhfe/2qDH5cg==";
      };
    };
    "property-expr-2.0.5" = {
      name = "property-expr";
      packageName = "property-expr";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/property-expr/-/property-expr-2.0.5.tgz";
        sha512 = "IJUkICM5dP5znhCckHSv30Q4b5/JA5enCtkRHYaOVOAocnH/1BQEYTC5NMfT3AVl/iXKdr3aqQbQn9DxyWknwA==";
      };
    };
    "react-18.2.0" = {
      name = "react";
      packageName = "react";
      version = "18.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-18.2.0.tgz";
        sha512 = "/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fGQ==";
      };
    };
    "react-ace-10.1.0" = {
      name = "react-ace";
      packageName = "react-ace";
      version = "10.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-ace/-/react-ace-10.1.0.tgz";
        sha512 = "VkvUjZNhdYTuKOKQpMIZi7uzZZVgzCjM7cLYu6F64V0mejY8a2XTyPUIMszC6A4trbeMIHbK5fYFcT/wkP/8VA==";
      };
    };
    "react-hook-form-7.34.0" = {
      name = "react-hook-form";
      packageName = "react-hook-form";
      version = "7.34.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-hook-form/-/react-hook-form-7.34.0.tgz";
        sha512 = "s0/TJ09NVlEk2JPp3yit1WnMuPNBXFmUKEQPulgDi9pYBw/ZmmAFHe6AXWq73Y+kp8ye4OcMf0Jv+i/qLPektg==";
      };
    };
    "react-is-16.13.1" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz";
        sha512 = "24e6ynE2H+OKt4kqsOvNd8kBpV65zoxbA4BVsEOB3ARVWQki/DHzaUoC5KuON/BiccDaCCTZBuOcfZs70kR8bQ==";
      };
    };
    "react-universal-interface-0.6.2" = {
      name = "react-universal-interface";
      packageName = "react-universal-interface";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-universal-interface/-/react-universal-interface-0.6.2.tgz";
        sha512 = "dg8yXdcQmvgR13RIlZbTRQOoUrDciFVoSBZILwjE2LFISxZZ8loVJKAkuzswl5js8BHda79bIb2b84ehU8IjXw==";
      };
    };
    "react-use-17.4.0" = {
      name = "react-use";
      packageName = "react-use";
      version = "17.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-use/-/react-use-17.4.0.tgz";
        sha512 = "TgbNTCA33Wl7xzIJegn1HndB4qTS9u03QUwyNycUnXaweZkE4Kq2SB+Yoxx8qbshkZGYBDvUXbXWRUmQDcZZ/Q==";
      };
    };
    "react-vega-7.6.0" = {
      name = "react-vega";
      packageName = "react-vega";
      version = "7.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-vega/-/react-vega-7.6.0.tgz";
        sha512 = "2oMML4wH9qWLnZPRxJm06ozwrVN/K+nkjqdI5/ofWWsrBnnH4iB9rRKrsV8px0nlWgZrwfdCH4g5RUiyyJHWSA==";
      };
    };
    "readable-stream-2.3.7" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.7.tgz";
        sha512 = "Ebho8K4jIbHAxnuxi7o42OrZgF/ZTNcsZj6nRKyUmkhLFq8CHItp/fy6hQZuZmP/n3yZ9VBUbp4zz/mX8hmYPw==";
      };
    };
    "regenerator-runtime-0.13.9" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.9.tgz";
        sha512 = "p3VT+cOEgxFsRRA9X4lkI1E+k2/CtnKtU4gcxyaCUreilL/vqI6CdZ3wxVUx3UOUg+gnUOQQcRI7BmSI656MYA==";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha512 = "fGxEI7+wsG9xrvdjsrlmL22OMTTiHRwAMroiEeMgq8gzoLC/PQr7RsRDSTLUg/bZAZtF+TVIkHc6/4RIKrui+Q==";
      };
    };
    "resize-observer-polyfill-1.5.1" = {
      name = "resize-observer-polyfill";
      packageName = "resize-observer-polyfill";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resize-observer-polyfill/-/resize-observer-polyfill-1.5.1.tgz";
        sha512 = "LwZrotdHOo12nQuZlHEmtuXdqGoOD0OhaxopaNFxWzInpEgaLWoVuAMbTzixuosCx2nEG58ngzW3vxdWoxIgdg==";
      };
    };
    "robust-predicates-3.0.1" = {
      name = "robust-predicates";
      packageName = "robust-predicates";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/robust-predicates/-/robust-predicates-3.0.1.tgz";
        sha512 = "ndEIpszUHiG4HtDsQLeIuMvRsDnn8c8rYStabochtUeCvfuvNptb5TUbVD68LRAILPX7p9nqQGh4xJgn3EHS/g==";
      };
    };
    "rtl-css-js-1.16.0" = {
      name = "rtl-css-js";
      packageName = "rtl-css-js";
      version = "1.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rtl-css-js/-/rtl-css-js-1.16.0.tgz";
        sha512 = "Oc7PnzwIEU4M0K1J4h/7qUUaljXhQ0kCObRsZjxs2HjkpKsnoTMvSmvJ4sqgJZd0zBoEfAyTdnK/jMIYvrjySQ==";
      };
    };
    "rw-1.3.3" = {
      name = "rw";
      packageName = "rw";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/rw/-/rw-1.3.3.tgz";
        sha512 = "PdhdWy89SiZogBLaw42zdeqtRJ//zFd2PgQavcICDUgJT5oW10QCRKbJ6bg4r0/UY2M6BWd5tkxuGFRvCkgfHQ==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "screenfull-5.2.0" = {
      name = "screenfull";
      packageName = "screenfull";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/screenfull/-/screenfull-5.2.0.tgz";
        sha512 = "9BakfsO2aUQN2K9Fdbj87RJIEZ82Q9IGim7FqM5OsebfoFC6ZHXgDq/KvniuLTPdeM8wY2o6Dj3WQ7KeQCj3cA==";
      };
    };
    "seedrandom-3.0.5" = {
      name = "seedrandom";
      packageName = "seedrandom";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/seedrandom/-/seedrandom-3.0.5.tgz";
        sha512 = "8OwmbklUNzwezjGInmZ+2clQmExQPvomqjL7LFqOYqtmuxRgQYqOD3mHaU+MvZn5FLUeVxVfQjwLZW/n/JFuqg==";
      };
    };
    "semver-7.3.7" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.7.tgz";
        sha512 = "QlYTucUYOews+WeEujDoEGziz4K6c47V/Bd+LjSSYcA94p+DmINdf7ncaUinThfvZyu13lN9OY1XDxt8C0Tw0g==";
      };
    };
    "set-harmonic-interval-1.0.1" = {
      name = "set-harmonic-interval";
      packageName = "set-harmonic-interval";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-harmonic-interval/-/set-harmonic-interval-1.0.1.tgz";
        sha512 = "AhICkFV84tBP1aWqPwLZqFvAwqEoVA9kxNMniGEUvzOlm4vLmOFLiTT3UZ6bziJTy4bOVpzWGTfSCbmaayGx8g==";
      };
    };
    "source-map-0.5.6" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.6.tgz";
        sha512 = "MjZkVp0NHr5+TPihLcadqnlVoGIoWo4IBHptutGh9wI3ttUYvCG26HkSuDi+K6lsZ25syXJXcctwgyVCt//xqA==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "sourcemap-codec-1.4.8" = {
      name = "sourcemap-codec";
      packageName = "sourcemap-codec";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/sourcemap-codec/-/sourcemap-codec-1.4.8.tgz";
        sha512 = "9NykojV5Uih4lgo5So5dtw+f0JgJX30KCNI8gwhz2J9A15wD0Ml6tjHKwf6fTSa6fAdVBdZeNOs9eJ71qCk8vA==";
      };
    };
    "stack-generator-2.0.10" = {
      name = "stack-generator";
      packageName = "stack-generator";
      version = "2.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-generator/-/stack-generator-2.0.10.tgz";
        sha512 = "mwnua/hkqM6pF4k8SnmZ2zfETsRUpWXREfA/goT8SLCV4iOFa4bzOX2nDipWAZFPTjLvQB82f5yaodMVhK0yJQ==";
      };
    };
    "stackframe-1.3.4" = {
      name = "stackframe";
      packageName = "stackframe";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/stackframe/-/stackframe-1.3.4.tgz";
        sha512 = "oeVtt7eWQS+Na6F//S4kJ2K2VbRlS9D43mAlMyVpVWovy9o+jfgH8O9agzANzaiLjclA0oYzUXEM4PurhSUChw==";
      };
    };
    "stacktrace-gps-3.1.2" = {
      name = "stacktrace-gps";
      packageName = "stacktrace-gps";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stacktrace-gps/-/stacktrace-gps-3.1.2.tgz";
        sha512 = "GcUgbO4Jsqqg6RxfyTHFiPxdPqF+3LFmQhm7MgCuYQOYuWyqxo5pwRPz5d/u6/WYJdEnWfK4r+jGbyD8TSggXQ==";
      };
    };
    "stacktrace-js-2.0.2" = {
      name = "stacktrace-js";
      packageName = "stacktrace-js";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stacktrace-js/-/stacktrace-js-2.0.2.tgz";
        sha512 = "Je5vBeY4S1r/RnLydLl0TBTi3F2qdfWmYsGvtfZgEI+SCprPppaIhQf5nGcal4gI4cGpCV/duLcAzT1np6sQqg==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "style-value-types-5.0.0" = {
      name = "style-value-types";
      packageName = "style-value-types";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/style-value-types/-/style-value-types-5.0.0.tgz";
        sha512 = "08yq36Ikn4kx4YU6RD7jWEv27v4V+PUsOGa4n/as8Et3CuODMJQ00ENeAVXAeydX4Z2j1XHZF1K2sX4mGl18fA==";
      };
    };
    "stylis-4.1.1" = {
      name = "stylis";
      packageName = "stylis";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylis/-/stylis-4.1.1.tgz";
        sha512 = "lVrM/bNdhVX2OgBFNa2YJ9Lxj7kPzylieHd3TNjuGE0Re9JB7joL5VUKOVH1kdNNJTgGPpT8hmwIAPLaSyEVFQ==";
      };
    };
    "throttle-debounce-3.0.1" = {
      name = "throttle-debounce";
      packageName = "throttle-debounce";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/throttle-debounce/-/throttle-debounce-3.0.1.tgz";
        sha512 = "dTEWWNu6JmeVXY0ZYoPuH5cRIwc0MeGbJwah9KUNYSJwommQpCzTySTpEe8Gs1J23aeWEuAobe4Ag7EHVt/LOg==";
      };
    };
    "tiny-emitter-2.1.0" = {
      name = "tiny-emitter";
      packageName = "tiny-emitter";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-emitter/-/tiny-emitter-2.1.0.tgz";
        sha512 = "NB6Dk1A9xgQPMoGqC5CVXn123gWyte215ONT5Pp5a0yt4nlEoO1ZWeCwpncaekPHXO60i47ihFnZPiRPjRMq4Q==";
      };
    };
    "toggle-selection-1.0.6" = {
      name = "toggle-selection";
      packageName = "toggle-selection";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/toggle-selection/-/toggle-selection-1.0.6.tgz";
        sha512 = "BiZS+C1OS8g/q2RRbJmy59xpyghNBqrr6k5L/uKBGRsTfxmu3ffiRnd8mlGPUVayg8pvfi5urfnu8TU7DVOkLQ==";
      };
    };
    "topojson-client-3.1.0" = {
      name = "topojson-client";
      packageName = "topojson-client";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/topojson-client/-/topojson-client-3.1.0.tgz";
        sha512 = "605uxS6bcYxGXw9qi62XyrV6Q3xwbndjachmNxu8HWTtVPxZfEJN9fd/SZS1Q54Sn2y0TMyMxFj/cJINqGHrKw==";
      };
    };
    "toposort-2.0.2" = {
      name = "toposort";
      packageName = "toposort";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/toposort/-/toposort-2.0.2.tgz";
        sha512 = "0a5EOkAUp8D4moMi2W8ZF8jcga7BgZd91O/yabJCFY8az+XSzeGyTKs0Aoo897iV1Nj6guFq8orWDS96z91oGg==";
      };
    };
    "tr46-0.0.3" = {
      name = "tr46";
      packageName = "tr46";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz";
        sha512 = "N3WMsuqV66lT30CrXNbEjx4GEwlow3v6rr4mCcv6prnfwhS01rkgyFdjPNBYd9br7LpXV1+Emh01fHnq2Gdgrw==";
      };
    };
    "ts-easing-0.2.0" = {
      name = "ts-easing";
      packageName = "ts-easing";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-easing/-/ts-easing-0.2.0.tgz";
        sha512 = "Z86EW+fFFh/IFB1fqQ3/+7Zpf9t2ebOAxNI/V6Wo7r5gqiqtxmgTlQ1qbqQcjLKYeSHPTsEmvlJUDg/EuL0uHQ==";
      };
    };
    "tslib-1.14.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.14.1.tgz";
        sha512 = "Xni35NKzjgMrwevysHTCArtLDpPvye8zV/0E4EyYn43P7/7qvQwPh9BGkHewbMulVntbigmcT7rdX3BNo9wRJg==";
      };
    };
    "tslib-2.4.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.4.0.tgz";
        sha512 = "d6xOpEDfsi2CZVlPQzGeux8XMwLT9hssAsaPYExaQMuYskwb+x1x7J371tWlbBdWHroy99KnVB6qIkUbs5X3UQ==";
      };
    };
    "typed-function-3.0.0" = {
      name = "typed-function";
      packageName = "typed-function";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-function/-/typed-function-3.0.0.tgz";
        sha512 = "mKJKkt2xYxJUuMD7jyfgUxfn5KCsCxkEKBVjep5yYellJJ5aEDO2QUAmIGdvcZmfQnIrplkzELIaG+5b1475qg==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "vega-5.22.1" = {
      name = "vega";
      packageName = "vega";
      version = "5.22.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega/-/vega-5.22.1.tgz";
        sha512 = "KJBI7OWSzpfCPbmWl3GQCqBqbf2TIdpWS0mzO6MmWbvdMhWHf74P9IVnx1B1mhg0ZTqWFualx9ZYhWzMMwudaQ==";
      };
    };
    "vega-canvas-1.2.6" = {
      name = "vega-canvas";
      packageName = "vega-canvas";
      version = "1.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-canvas/-/vega-canvas-1.2.6.tgz";
        sha512 = "rgeYUpslYn/amIfnuv3Sw6n4BGns94OjjZNtUc9IDji6b+K8LGS/kW+Lvay8JX/oFqtulBp8RLcHN6QjqPLA9Q==";
      };
    };
    "vega-crossfilter-4.1.0" = {
      name = "vega-crossfilter";
      packageName = "vega-crossfilter";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-crossfilter/-/vega-crossfilter-4.1.0.tgz";
        sha512 = "aiOJcvVpiEDIu5uNc4Kf1hakkkPaVOO5fw5T4RSFAw6GEDbdqcB6eZ1xePcsLVic1hxYD5SGiUPdiiIs0SMh2g==";
      };
    };
    "vega-dataflow-5.7.4" = {
      name = "vega-dataflow";
      packageName = "vega-dataflow";
      version = "5.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-dataflow/-/vega-dataflow-5.7.4.tgz";
        sha512 = "JGHTpUo8XGETH3b1V892we6hdjzCWB977ybycIu8DPqRoyrZuj6t1fCVImazfMgQD1LAfJlQybWP+alwKDpKig==";
      };
    };
    "vega-embed-6.21.0" = {
      name = "vega-embed";
      packageName = "vega-embed";
      version = "6.21.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-embed/-/vega-embed-6.21.0.tgz";
        sha512 = "Tzo9VAfgNRb6XpxSFd7uphSeK2w5OxDY2wDtmpsQ+rQlPSEEI9TE6Jsb2nHRLD5J4FrmXKLrTcORqidsNQSXEg==";
      };
    };
    "vega-encode-4.9.0" = {
      name = "vega-encode";
      packageName = "vega-encode";
      version = "4.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-encode/-/vega-encode-4.9.0.tgz";
        sha512 = "etv2BHuCn9bzEc0cxyA2TnbtcAFQGVFmsaqmB4sgBCaqTSEfXMoX68LK3yxBrsdm5LU+y3otJVoewi3qWYCx2g==";
      };
    };
    "vega-event-selector-3.0.0" = {
      name = "vega-event-selector";
      packageName = "vega-event-selector";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-event-selector/-/vega-event-selector-3.0.0.tgz";
        sha512 = "Gls93/+7tEJGE3kUuUnxrBIxtvaNeF01VIFB2Q2Of2hBIBvtHX74jcAdDtkh5UhhoYGD8Q1J30P5cqEBEwtPoQ==";
      };
    };
    "vega-expression-5.0.0" = {
      name = "vega-expression";
      packageName = "vega-expression";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-expression/-/vega-expression-5.0.0.tgz";
        sha512 = "y5+c2frq0tGwJ7vYXzZcfVcIRF/QGfhf2e+bV1Z0iQs+M2lI1II1GPDdmOcMKimpoCVp/D61KUJDIGE1DSmk2w==";
      };
    };
    "vega-force-4.1.0" = {
      name = "vega-force";
      packageName = "vega-force";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-force/-/vega-force-4.1.0.tgz";
        sha512 = "Sssf8iH48vYlz+E7/RpU+SUaJbuLoIL87U4tG2Av4gf/hRiImU49x2TI3EuhFWg1zpaCFxlz0CAaX++Oh/gjdw==";
      };
    };
    "vega-format-1.1.0" = {
      name = "vega-format";
      packageName = "vega-format";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-format/-/vega-format-1.1.0.tgz";
        sha512 = "6mgpeWw8yGdG0Zdi8aVkx5oUrpJGOpNxqazC2858RSDPvChM/jDFlgRMTYw52qk7cxU0L08ARp4BwmXaI75j0w==";
      };
    };
    "vega-functions-5.13.0" = {
      name = "vega-functions";
      packageName = "vega-functions";
      version = "5.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-functions/-/vega-functions-5.13.0.tgz";
        sha512 = "Mf53zNyx+c9fFqagEI0T8zc9nMlx0zozOngr8oOpG1tZDKOgwOnUgN99zQKbLHjyv+UzWrq3LYTnSLyVe0ZmhQ==";
      };
    };
    "vega-geo-4.4.0" = {
      name = "vega-geo";
      packageName = "vega-geo";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-geo/-/vega-geo-4.4.0.tgz";
        sha512 = "3YX41y+J5pu0PMjvBCASg0/lgvu9+QXWJZ+vl6FFKa8AlsIopQ67ZL7ObwqjZcoZMolJ4q0rc+ZO8aj1pXCYcw==";
      };
    };
    "vega-hierarchy-4.1.0" = {
      name = "vega-hierarchy";
      packageName = "vega-hierarchy";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-hierarchy/-/vega-hierarchy-4.1.0.tgz";
        sha512 = "DWBK39IEt4FiQru12twzKSFUvFFZ7KtlH9+lAaqrJnKuIZFCyQ1XOUfKScfbKIlk4KS+DuCTNLI/pxC/f7Sk9Q==";
      };
    };
    "vega-interpreter-1.0.4" = {
      name = "vega-interpreter";
      packageName = "vega-interpreter";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-interpreter/-/vega-interpreter-1.0.4.tgz";
        sha512 = "6tpYIa/pJz0cZo5fSxDSkZkAA51pID2LjOtQkOQvbzn+sJiCaWKPFhur8MBqbcmYZ9bnap1OYNwlrvpd2qBLvg==";
      };
    };
    "vega-label-1.2.0" = {
      name = "vega-label";
      packageName = "vega-label";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-label/-/vega-label-1.2.0.tgz";
        sha512 = "1prOqkCAfXaUvMqavbGI0nbYGqV8UQR9qvuVwrPJ6Yxm3GIUIOA/JRqNY8eZR8USwMP/kzsqlfVEixj9+Y75VQ==";
      };
    };
    "vega-lite-5.4.0" = {
      name = "vega-lite";
      packageName = "vega-lite";
      version = "5.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-lite/-/vega-lite-5.4.0.tgz";
        sha512 = "e/P5iOtBE62WEWZhKP7sLcBd92YS9prfUQafelxoOeloooSSrkUwM/ZDmN5Q5ffByEZTiKfODtnwD6/xKDYUmw==";
      };
    };
    "vega-loader-4.5.0" = {
      name = "vega-loader";
      packageName = "vega-loader";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-loader/-/vega-loader-4.5.0.tgz";
        sha512 = "EkAyzbx0pCYxH3v3wghGVCaKINWxHfgbQ2pYDiYv0yo8e04S8Mv/IlRGTt6BAe7cLhrk1WZ4zh20QOppnGG05w==";
      };
    };
    "vega-parser-6.1.4" = {
      name = "vega-parser";
      packageName = "vega-parser";
      version = "6.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-parser/-/vega-parser-6.1.4.tgz";
        sha512 = "tORdpWXiH/kkXcpNdbSVEvtaxBuuDtgYp9rBunVW9oLsjFvFXbSWlM1wvJ9ZFSaTfx6CqyTyGMiJemmr1QnTjQ==";
      };
    };
    "vega-projection-1.5.0" = {
      name = "vega-projection";
      packageName = "vega-projection";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-projection/-/vega-projection-1.5.0.tgz";
        sha512 = "aob7qojh555x3hQWZ/tr8cIJNSWQbm6EoWTJaheZgFOY2x3cDa4Qrg3RJbGw6KwVj/IQk2p40paRzixKZ2kr+A==";
      };
    };
    "vega-regression-1.1.0" = {
      name = "vega-regression";
      packageName = "vega-regression";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-regression/-/vega-regression-1.1.0.tgz";
        sha512 = "09K0RemY6cdaXBAyakDUNFfEkRcLkGjkDJyWQPAUqGK59hV2J+G3i4uxkZp18Vu0t8oqU7CgzwWim1s5uEpOcA==";
      };
    };
    "vega-runtime-6.1.3" = {
      name = "vega-runtime";
      packageName = "vega-runtime";
      version = "6.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-runtime/-/vega-runtime-6.1.3.tgz";
        sha512 = "gE+sO2IfxMUpV0RkFeQVnHdmPy3K7LjHakISZgUGsDI/ZFs9y+HhBf8KTGSL5pcZPtQsZh3GBQ0UonqL1mp9PA==";
      };
    };
    "vega-scale-7.2.0" = {
      name = "vega-scale";
      packageName = "vega-scale";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-scale/-/vega-scale-7.2.0.tgz";
        sha512 = "QYltO/otrZHLrCGGf06Y99XtPtqWXITr6rw7rO9oL+l3d9o5RFl9sjHrVxiM7v+vGoZVWbBd5IPbFhPsXZ6+TA==";
      };
    };
    "vega-scenegraph-4.10.1" = {
      name = "vega-scenegraph";
      packageName = "vega-scenegraph";
      version = "4.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-scenegraph/-/vega-scenegraph-4.10.1.tgz";
        sha512 = "takIpkmNxYHhJYALOYzhTin3EDzbys6U4g+l1yJZVlXG9YTdiCMuEVAdtaQOCqF9/7qytD6pCrMxJY2HaoN0qQ==";
      };
    };
    "vega-schema-url-parser-2.2.0" = {
      name = "vega-schema-url-parser";
      packageName = "vega-schema-url-parser";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-schema-url-parser/-/vega-schema-url-parser-2.2.0.tgz";
        sha512 = "yAtdBnfYOhECv9YC70H2gEiqfIbVkq09aaE4y/9V/ovEFmH9gPKaEgzIZqgT7PSPQjKhsNkb6jk6XvSoboxOBw==";
      };
    };
    "vega-selections-5.4.0" = {
      name = "vega-selections";
      packageName = "vega-selections";
      version = "5.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-selections/-/vega-selections-5.4.0.tgz";
        sha512 = "Un3JdLDPjIpF9Dh4sw6m1c/QAcfam6m1YXHJ9vJxE/GdJ+sOrPxc7bcEU8VhOmTUN7IQUn4/1ry4JqqOVMbEhw==";
      };
    };
    "vega-statistics-1.8.0" = {
      name = "vega-statistics";
      packageName = "vega-statistics";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-statistics/-/vega-statistics-1.8.0.tgz";
        sha512 = "dl+LCRS6qS4jWDme/NEdPVt5r649uB4IK6Kyr2/czmGA5JqjuFmtQ9lHQOnRu8945XLkqLf+JIQQo7vnw+nslA==";
      };
    };
    "vega-themes-2.10.0" = {
      name = "vega-themes";
      packageName = "vega-themes";
      version = "2.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-themes/-/vega-themes-2.10.0.tgz";
        sha512 = "prePRUKFUFGWniuZsJOfkdb+27Gwrrm82yAlVuU+912kcknsx1DVmMSg2yF79f4jdtqnAFIGycZgxoj13SEIuQ==";
      };
    };
    "vega-time-2.1.0" = {
      name = "vega-time";
      packageName = "vega-time";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-time/-/vega-time-2.1.0.tgz";
        sha512 = "Q9/l3S6Br1RPX5HZvyLD/cQ4K6K8DtpR09/1y7D66gxNorg2+HGzYZINH9nUvN3mxoXcBWg4cCUh3+JvmkDaEg==";
      };
    };
    "vega-tooltip-0.28.0" = {
      name = "vega-tooltip";
      packageName = "vega-tooltip";
      version = "0.28.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-tooltip/-/vega-tooltip-0.28.0.tgz";
        sha512 = "DbK0V5zzk+p9cphZZXV91ZGeKq0zr6JIS0VndUoGTisldzw4tRgmpGQcTfMjew53o7/voeTM2ELTnJAJRzX4tg==";
      };
    };
    "vega-transforms-4.10.0" = {
      name = "vega-transforms";
      packageName = "vega-transforms";
      version = "4.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-transforms/-/vega-transforms-4.10.0.tgz";
        sha512 = "Yk6ByzVq5F2niFfPlSsrU5wi+NZhsF7IBpJCcTfms4U7eoyNepUXagdFEJ3VWBD/Lit6GorLXFgO17NYcyS5gg==";
      };
    };
    "vega-typings-0.22.3" = {
      name = "vega-typings";
      packageName = "vega-typings";
      version = "0.22.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-typings/-/vega-typings-0.22.3.tgz";
        sha512 = "PREcya3nXT9Tk7xU0IhEpOLVTlqizNtKXV55NhI6ApBjJtqVYbJL7IBh2ckKxGBy3YeUQ37BQZl56UqqiYVWBw==";
      };
    };
    "vega-util-1.17.0" = {
      name = "vega-util";
      packageName = "vega-util";
      version = "1.17.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-util/-/vega-util-1.17.0.tgz";
        sha512 = "HTaydZd9De3yf+8jH66zL4dXJ1d1p5OIFyoBzFiOli4IJbwkL1jrefCKz6AHDm1kYBzDJ0X4bN+CzZSCTvNk1w==";
      };
    };
    "vega-view-5.11.0" = {
      name = "vega-view";
      packageName = "vega-view";
      version = "5.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-view/-/vega-view-5.11.0.tgz";
        sha512 = "MI9NTRFmtFX6ADk6KOHhi8bhHjC9pPm42Bj2+74c6l1d3NQZf9Jv7lkiGqKohdkQDNH9LPwz/6slhKwPU9JdkQ==";
      };
    };
    "vega-view-transforms-4.5.8" = {
      name = "vega-view-transforms";
      packageName = "vega-view-transforms";
      version = "4.5.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-view-transforms/-/vega-view-transforms-4.5.8.tgz";
        sha512 = "966m7zbzvItBL8rwmF2nKG14rBp7q+3sLCKWeMSUrxoG+M15Smg5gWEGgwTG3A/RwzrZ7rDX5M1sRaAngRH25g==";
      };
    };
    "vega-voronoi-4.2.0" = {
      name = "vega-voronoi";
      packageName = "vega-voronoi";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-voronoi/-/vega-voronoi-4.2.0.tgz";
        sha512 = "1iuNAVZgUHRlBpdq4gSga3KlQmrgFfwy+KpyDgPLQ8HbLkhcVeT7RDh2L6naluqD7Op0xVLms3clR920WsYryQ==";
      };
    };
    "vega-wordcloud-4.1.3" = {
      name = "vega-wordcloud";
      packageName = "vega-wordcloud";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vega-wordcloud/-/vega-wordcloud-4.1.3.tgz";
        sha512 = "is4zYn9FMAyp9T4SAcz2P/U/wqc0Lx3P5YtpWKCbOH02a05vHjUQrQ2TTPOuvmMfAEDCSKvbMSQIJMOE018lJA==";
      };
    };
    "vscode-uri-3.0.3" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.0.3.tgz";
        sha512 = "EcswR2S8bpR7fD0YPeS7r2xXExrScVMxg4MedACaWHEtx9ftCF/qHG1xGkolzTPcEmjTavCQgbVzHUIdTMzFGA==";
      };
    };
    "webidl-conversions-3.0.1" = {
      name = "webidl-conversions";
      packageName = "webidl-conversions";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-3.0.1.tgz";
        sha512 = "2JAn3z8AR6rjK8Sm8orRC0h/bcl/DqL7tRPdGZ4I1CjdF+EaMLmYxBHyXuKL849eucPFhvBoxMsflfOb8kxaeQ==";
      };
    };
    "whatwg-url-5.0.0" = {
      name = "whatwg-url";
      packageName = "whatwg-url";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-url/-/whatwg-url-5.0.0.tgz";
        sha512 = "saE57nupxk6v3HY35+jzBwYa0rKSy0XR8JSxZPwgLr7ys0IBzhGviA1/TUGJLmSVqs8pb9AnvICXEuOHLprYTw==";
      };
    };
    "wrap-ansi-7.0.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "y18n-5.0.8" = {
      name = "y18n";
      packageName = "y18n";
      version = "5.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-5.0.8.tgz";
        sha512 = "0pfFzegeDWJHJIAmTLRP2DwHjdF5s7jo9tuztdQxAhINCdvS+3nGINqPd00AphqJR/0LhANUS6/+7SCb98YOfA==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yargs-17.5.1" = {
      name = "yargs";
      packageName = "yargs";
      version = "17.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-17.5.1.tgz";
        sha512 = "t6YAJcxDkNX7NFYiVtKvWUz8l+PaKTLiL63mJYWR2GnHq2gjEWISzsLp9wg3aY36dY1j+gfIEL3pIF+XlJJfbA==";
      };
    };
    "yargs-parser-21.0.1" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "21.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-21.0.1.tgz";
        sha512 = "9BK1jFpLzJROCI5TzwZL/TU4gqjK5xiHV/RfWLOahrjAko/e4DJkRDZQXfvqAsiZzzYhgAzbgz6lg48jcm4GLg==";
      };
    };
    "yup-0.32.11" = {
      name = "yup";
      packageName = "yup";
      version = "0.32.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/yup/-/yup-0.32.11.tgz";
        sha512 = "Z2Fe1bn+eLstG8DRR6FTavGD+MeAwyfmouhHsIUgaADz8jvFKbO/fXc2trJKZg+5EBjh4gGm3iU/t3onKlXHIg==";
      };
    };
  };
  args = {
    name = "_at_quri_slash_squiggle-components";
    packageName = "@quri/squiggle-components";
    version = "0.2.24";
    src = ./.;
    dependencies = [
      sources."@babel/runtime-7.18.9"
      sources."@emotion/is-prop-valid-0.8.8"
      sources."@emotion/memoize-0.7.4"
      sources."@floating-ui/core-1.0.0"
      sources."@floating-ui/dom-1.0.0"
      sources."@floating-ui/react-dom-1.0.0"
      sources."@floating-ui/react-dom-interactions-0.9.1"
      sources."@headlessui/react-1.6.6"
      sources."@heroicons/react-1.0.6"
      sources."@hookform/resolvers-2.9.7"
      sources."@juggle/resize-observer-3.3.1"
      (sources."@motionone/animation-10.13.1" // {
        dependencies = [
          sources."tslib-2.4.0"
        ];
      })
      (sources."@motionone/dom-10.12.0" // {
        dependencies = [
          sources."tslib-2.4.0"
        ];
      })
      (sources."@motionone/easing-10.13.1" // {
        dependencies = [
          sources."tslib-2.4.0"
        ];
      })
      (sources."@motionone/generators-10.13.1" // {
        dependencies = [
          sources."tslib-2.4.0"
        ];
      })
      sources."@motionone/types-10.13.0"
      (sources."@motionone/utils-10.13.1" // {
        dependencies = [
          sources."tslib-2.4.0"
        ];
      })
      sources."@quri/squiggle-lang-0.2.12"
      sources."@react-hook/latest-1.0.3"
      sources."@react-hook/passive-layout-effect-1.2.1"
      sources."@react-hook/resize-observer-1.2.6"
      sources."@react-hook/size-2.1.2"
      sources."@rescript/std-9.1.4"
      sources."@stdlib/array-0.0.12"
      sources."@stdlib/assert-0.0.12"
      sources."@stdlib/bigint-0.0.11"
      sources."@stdlib/blas-0.0.12"
      sources."@stdlib/buffer-0.0.11"
      sources."@stdlib/cli-0.0.10"
      sources."@stdlib/complex-0.0.12"
      sources."@stdlib/constants-0.0.11"
      sources."@stdlib/fs-0.0.12"
      sources."@stdlib/math-0.0.11"
      sources."@stdlib/ndarray-0.0.13"
      sources."@stdlib/nlp-0.0.11"
      sources."@stdlib/number-0.0.10"
      sources."@stdlib/os-0.0.12"
      sources."@stdlib/process-0.0.12"
      sources."@stdlib/random-0.0.12"
      sources."@stdlib/regexp-0.0.13"
      sources."@stdlib/stats-0.0.13"
      sources."@stdlib/streams-0.0.12"
      sources."@stdlib/strided-0.0.12"
      sources."@stdlib/string-0.0.14"
      sources."@stdlib/symbol-0.0.12"
      sources."@stdlib/time-0.0.14"
      sources."@stdlib/types-0.0.14"
      sources."@stdlib/utils-0.0.12"
      sources."@types/clone-2.1.1"
      sources."@types/estree-0.0.50"
      sources."@types/js-cookie-2.2.7"
      sources."@types/lodash-4.14.182"
      sources."@types/prop-types-15.7.5"
      sources."@types/react-18.0.15"
      sources."@types/scheduler-0.16.2"
      sources."@xobotyi/scrollbar-width-1.9.5"
      sources."ace-builds-1.8.1"
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-4.3.0"
      sources."aria-hidden-1.1.3"
      sources."array-flat-polyfill-1.0.1"
      sources."cliui-7.0.4"
      sources."clone-2.1.2"
      sources."clsx-1.2.1"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."commander-7.2.0"
      sources."complex.js-2.1.1"
      sources."copy-to-clipboard-3.3.1"
      sources."core-util-is-1.0.3"
      sources."css-in-js-utils-2.0.1"
      sources."css-tree-1.1.3"
      sources."csstype-3.1.0"
      sources."d3-array-3.2.0"
      sources."d3-color-3.1.0"
      sources."d3-delaunay-6.0.2"
      sources."d3-dispatch-3.0.1"
      sources."d3-dsv-3.0.1"
      sources."d3-force-3.0.0"
      sources."d3-format-3.1.0"
      sources."d3-geo-3.0.1"
      sources."d3-geo-projection-4.0.0"
      sources."d3-hierarchy-3.1.2"
      sources."d3-interpolate-3.0.1"
      sources."d3-path-3.0.1"
      sources."d3-quadtree-3.0.1"
      sources."d3-scale-4.0.2"
      sources."d3-shape-3.1.0"
      sources."d3-time-3.0.0"
      sources."d3-time-format-4.1.0"
      sources."d3-timer-3.0.1"
      sources."debug-2.6.9"
      sources."decimal.js-10.3.1"
      sources."delaunator-5.0.0"
      sources."diff-match-patch-1.0.5"
      sources."emoji-regex-8.0.0"
      sources."error-stack-parser-2.1.4"
      sources."escalade-3.1.1"
      sources."escape-latex-1.2.0"
      sources."fast-deep-equal-3.1.3"
      sources."fast-json-patch-3.1.1"
      sources."fast-json-stable-stringify-2.1.0"
      sources."fast-shallow-equal-1.0.0"
      sources."fastest-stable-stringify-2.0.2"
      sources."fraction.js-4.2.0"
      (sources."framer-motion-6.5.1" // {
        dependencies = [
          sources."tslib-2.4.0"
        ];
      })
      (sources."framesync-6.0.1" // {
        dependencies = [
          sources."tslib-2.4.0"
        ];
      })
      sources."get-caller-file-2.0.5"
      sources."hey-listen-1.0.8"
      sources."hyphenate-style-name-1.0.4"
      sources."iconv-lite-0.6.3"
      sources."inherits-2.0.4"
      sources."inline-style-prefixer-6.0.1"
      sources."internmap-2.0.3"
      sources."is-fullwidth-code-point-3.0.0"
      sources."isarray-1.0.0"
      sources."isobject-3.0.1"
      sources."javascript-natural-sort-0.7.1"
      sources."js-cookie-2.2.1"
      sources."js-tokens-4.0.0"
      sources."json-stringify-pretty-compact-3.0.0"
      sources."jstat-1.9.5"
      sources."lodash-4.17.21"
      sources."lodash-es-4.17.21"
      sources."lodash.get-4.4.2"
      sources."lodash.isequal-4.5.0"
      sources."loose-envify-1.4.0"
      sources."lru-cache-6.0.0"
      sources."mathjs-11.0.1"
      sources."mdn-data-2.0.14"
      sources."minimist-1.2.6"
      sources."ms-2.0.0"
      sources."nano-css-5.3.5"
      sources."nanoclone-0.2.1"
      sources."node-fetch-2.6.7"
      sources."object-assign-4.1.1"
      sources."pdfast-0.2.0"
      (sources."popmotion-11.0.3" // {
        dependencies = [
          sources."tslib-2.4.0"
        ];
      })
      sources."process-nextick-args-2.0.1"
      sources."prop-types-15.8.1"
      sources."property-expr-2.0.5"
      sources."react-18.2.0"
      sources."react-ace-10.1.0"
      sources."react-hook-form-7.34.0"
      sources."react-is-16.13.1"
      sources."react-universal-interface-0.6.2"
      (sources."react-use-17.4.0" // {
        dependencies = [
          sources."tslib-2.4.0"
        ];
      })
      sources."react-vega-7.6.0"
      sources."readable-stream-2.3.7"
      sources."regenerator-runtime-0.13.9"
      sources."require-directory-2.1.1"
      sources."resize-observer-polyfill-1.5.1"
      sources."robust-predicates-3.0.1"
      sources."rtl-css-js-1.16.0"
      sources."rw-1.3.3"
      sources."safe-buffer-5.1.2"
      sources."safer-buffer-2.1.2"
      sources."screenfull-5.2.0"
      sources."seedrandom-3.0.5"
      sources."semver-7.3.7"
      sources."set-harmonic-interval-1.0.1"
      sources."source-map-0.6.1"
      sources."sourcemap-codec-1.4.8"
      sources."stack-generator-2.0.10"
      sources."stackframe-1.3.4"
      (sources."stacktrace-gps-3.1.2" // {
        dependencies = [
          sources."source-map-0.5.6"
        ];
      })
      sources."stacktrace-js-2.0.2"
      sources."string-width-4.2.3"
      sources."string_decoder-1.1.1"
      sources."strip-ansi-6.0.1"
      (sources."style-value-types-5.0.0" // {
        dependencies = [
          sources."tslib-2.4.0"
        ];
      })
      sources."stylis-4.1.1"
      sources."throttle-debounce-3.0.1"
      sources."tiny-emitter-2.1.0"
      sources."toggle-selection-1.0.6"
      (sources."topojson-client-3.1.0" // {
        dependencies = [
          sources."commander-2.20.3"
        ];
      })
      sources."toposort-2.0.2"
      sources."tr46-0.0.3"
      sources."ts-easing-0.2.0"
      sources."tslib-1.14.1"
      sources."typed-function-3.0.0"
      sources."util-deprecate-1.0.2"
      sources."vega-5.22.1"
      sources."vega-canvas-1.2.6"
      sources."vega-crossfilter-4.1.0"
      sources."vega-dataflow-5.7.4"
      (sources."vega-embed-6.21.0" // {
        dependencies = [
          sources."tslib-2.4.0"
        ];
      })
      sources."vega-encode-4.9.0"
      sources."vega-event-selector-3.0.0"
      sources."vega-expression-5.0.0"
      sources."vega-force-4.1.0"
      sources."vega-format-1.1.0"
      sources."vega-functions-5.13.0"
      sources."vega-geo-4.4.0"
      sources."vega-hierarchy-4.1.0"
      sources."vega-interpreter-1.0.4"
      sources."vega-label-1.2.0"
      (sources."vega-lite-5.4.0" // {
        dependencies = [
          sources."tslib-2.4.0"
        ];
      })
      sources."vega-loader-4.5.0"
      sources."vega-parser-6.1.4"
      sources."vega-projection-1.5.0"
      sources."vega-regression-1.1.0"
      sources."vega-runtime-6.1.3"
      sources."vega-scale-7.2.0"
      sources."vega-scenegraph-4.10.1"
      sources."vega-schema-url-parser-2.2.0"
      (sources."vega-selections-5.4.0" // {
        dependencies = [
          sources."d3-array-3.1.1"
        ];
      })
      sources."vega-statistics-1.8.0"
      sources."vega-themes-2.10.0"
      sources."vega-time-2.1.0"
      sources."vega-tooltip-0.28.0"
      sources."vega-transforms-4.10.0"
      sources."vega-typings-0.22.3"
      sources."vega-util-1.17.0"
      sources."vega-view-5.11.0"
      sources."vega-view-transforms-4.5.8"
      sources."vega-voronoi-4.2.0"
      sources."vega-wordcloud-4.1.3"
      sources."vscode-uri-3.0.3"
      sources."webidl-conversions-3.0.1"
      sources."whatwg-url-5.0.0"
      sources."wrap-ansi-7.0.0"
      sources."y18n-5.0.8"
      sources."yallist-4.0.0"
      sources."yargs-17.5.1"
      sources."yargs-parser-21.0.1"
      sources."yup-0.32.11"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
