# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/runtime-7.18.9" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.18.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.18.9.tgz";
        sha512 = "lkqXDcvlFT5rvEjiu6+QYO+1GXrEHRo2LOtS7E4GtX5ESIZOgepqsZBVIj6Pv+a6zqsya9VCgiK1KAK4BvJDAw==";
      };
    };
    "@rescript/std-9.1.4" = {
      name = "_at_rescript_slash_std";
      packageName = "@rescript/std";
      version = "9.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rescript/std/-/std-9.1.4.tgz";
        sha512 = "OHBORysVe6vmyllL24S2sXiwLGrpVRbZW5k2FverbjY3QF81VoyCRYL6kMOSNMEn9GseO/oDubK8+nvVzCSVMA==";
      };
    };
    "@stdlib/array-0.0.12" = {
      name = "_at_stdlib_slash_array";
      packageName = "@stdlib/array";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/array/-/array-0.0.12.tgz";
        sha512 = "nDksiuvRC1dSTHrf5yOGQmlRwAzSKV8MdFQwFSvLbZGGhi5Y4hExqea5HloLgNVouVs8lnAFi2oubSM4Mc7YAg==";
      };
    };
    "@stdlib/assert-0.0.12" = {
      name = "_at_stdlib_slash_assert";
      packageName = "@stdlib/assert";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/assert/-/assert-0.0.12.tgz";
        sha512 = "38FxFf+ZoQZbdc+m09UsWtaCmzd/2e7im0JOaaFYE7icmRfm+4KiE9BRvBT4tIn7ioLB2f9PsBicKjIsf+tY1w==";
      };
    };
    "@stdlib/bigint-0.0.11" = {
      name = "_at_stdlib_slash_bigint";
      packageName = "@stdlib/bigint";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/bigint/-/bigint-0.0.11.tgz";
        sha512 = "uz0aYDLABAYyqxaCSHYbUt0yPkXYUCR7TrVvHN+UUD3i8FZ02ZKcLO+faKisDyxKEoSFTNtn3Ro8Ir5ebOlVXQ==";
      };
    };
    "@stdlib/blas-0.0.12" = {
      name = "_at_stdlib_slash_blas";
      packageName = "@stdlib/blas";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/blas/-/blas-0.0.12.tgz";
        sha512 = "nWY749bWceuoWQ7gz977blCwR7lyQ/rsIXVO4b600h+NFpeA2i/ea7MYC680utIbeu2cnDWHdglBPoK535VAzA==";
      };
    };
    "@stdlib/buffer-0.0.11" = {
      name = "_at_stdlib_slash_buffer";
      packageName = "@stdlib/buffer";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/buffer/-/buffer-0.0.11.tgz";
        sha512 = "Jeie5eDDa1tVuRcuU+cBXI/oOXSmMxUUccZpqXzgYe0IO8QSNtNxv9mUTzJk/m5wH+lmLoDvNxzPpOH9TODjJg==";
      };
    };
    "@stdlib/cli-0.0.10" = {
      name = "_at_stdlib_slash_cli";
      packageName = "@stdlib/cli";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/cli/-/cli-0.0.10.tgz";
        sha512 = "OITGaxG46kwK799+NuOd/+ccosJ9koVuQBC610DDJv0ZJf8mD7sbjGXrmue9C4EOh8MP7Vm/6HN14BojX8oTCg==";
      };
    };
    "@stdlib/complex-0.0.12" = {
      name = "_at_stdlib_slash_complex";
      packageName = "@stdlib/complex";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/complex/-/complex-0.0.12.tgz";
        sha512 = "UbZBdaUxT2G+lsTIrVlRZwx2IRY6GXnVILggeejsIVxHSuK+oTyapfetcAv0FJFLP+Rrr+ZzrN4b9G3hBw6NHA==";
      };
    };
    "@stdlib/constants-0.0.11" = {
      name = "_at_stdlib_slash_constants";
      packageName = "@stdlib/constants";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/constants/-/constants-0.0.11.tgz";
        sha512 = "cWKy0L9hXHUQTvFzdPkTvZnn/5Pjv7H4UwY0WC1rLt+A5CxFDJKjvnIi9ypSzJS3CAiGl1ZaHCdadoqXhNdkUg==";
      };
    };
    "@stdlib/fs-0.0.12" = {
      name = "_at_stdlib_slash_fs";
      packageName = "@stdlib/fs";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/fs/-/fs-0.0.12.tgz";
        sha512 = "zcDLbt39EEM3M3wJW6luChS53B8T+TMJkjs2526UpKJ71O0/0adR57cI7PfCpkMd33d05uM7GM+leEj4eks4Cw==";
      };
    };
    "@stdlib/math-0.0.11" = {
      name = "_at_stdlib_slash_math";
      packageName = "@stdlib/math";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/math/-/math-0.0.11.tgz";
        sha512 = "qI78sR1QqGjHj8k/aAqkZ51Su2fyBvaR/jMKQqcB/ML8bpYpf+QGlGvTty5Qdru/wpqds4kVFOVbWGcNFIV2+Q==";
      };
    };
    "@stdlib/ndarray-0.0.13" = {
      name = "_at_stdlib_slash_ndarray";
      packageName = "@stdlib/ndarray";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/ndarray/-/ndarray-0.0.13.tgz";
        sha512 = "Z+U9KJP4U2HWrLtuAXSPvhNetAdqaNLMcliR6S/fz+VPlFDeymRK7omRFMgVQ+1zcAvIgKZGJxpLC3vjiPUYEw==";
      };
    };
    "@stdlib/nlp-0.0.11" = {
      name = "_at_stdlib_slash_nlp";
      packageName = "@stdlib/nlp";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/nlp/-/nlp-0.0.11.tgz";
        sha512 = "D9avYWANm0Db2W7RpzdSdi5GxRYALGAqUrNnRnnKIO6sMEfr/DvONoAbWruda4QyvSC+0MJNwcEn7+PHhRwYhw==";
      };
    };
    "@stdlib/number-0.0.10" = {
      name = "_at_stdlib_slash_number";
      packageName = "@stdlib/number";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/number/-/number-0.0.10.tgz";
        sha512 = "RyfoP9MlnX4kccvg8qv7vYQPbLdzfS1Mnp/prGOoWhvMG3pyBwFAan34kwFb5IS/zHC3W5EmrgXCV2QWyLg/Kg==";
      };
    };
    "@stdlib/os-0.0.12" = {
      name = "_at_stdlib_slash_os";
      packageName = "@stdlib/os";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/os/-/os-0.0.12.tgz";
        sha512 = "O7lklZ/9XEzoCmYvzjPh7jrFWkbpOSHGI71ve3dkSvBy5tyiSL3TtivfKsIC+9ZxuEJZ3d3lIjc9e+yz4HVbqQ==";
      };
    };
    "@stdlib/process-0.0.12" = {
      name = "_at_stdlib_slash_process";
      packageName = "@stdlib/process";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/process/-/process-0.0.12.tgz";
        sha512 = "P0X0TMvkissBE1Wr877Avi2/AxmP7X5Toa6GatHbpJdDg6jQmN4SgPd+NZNp98YtZUyk478c8XSIzMr1krQ20g==";
      };
    };
    "@stdlib/random-0.0.12" = {
      name = "_at_stdlib_slash_random";
      packageName = "@stdlib/random";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/random/-/random-0.0.12.tgz";
        sha512 = "c5yND4Ahnm9Jx0I+jsKhn4Yrz10D53ALSrIe3PG1qIz3kNFcIPnmvCuNGd+3V4ch4Mbrez55Y8z/ZC5RJh4vJQ==";
      };
    };
    "@stdlib/regexp-0.0.13" = {
      name = "_at_stdlib_slash_regexp";
      packageName = "@stdlib/regexp";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/regexp/-/regexp-0.0.13.tgz";
        sha512 = "3JT5ZIoq/1nXY+dY+QtkU8/m7oWDeekyItEEXMx9c/AOf0ph8fmvTUGMDNfUq0RetcznFe3b66kFz6Zt4XHviA==";
      };
    };
    "@stdlib/stats-0.0.13" = {
      name = "_at_stdlib_slash_stats";
      packageName = "@stdlib/stats";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/stats/-/stats-0.0.13.tgz";
        sha512 = "hm+t32dKbx/L7+7WlQ1o4NDEzV0J4QSnwFBCsIMIAO8+VPxTZ4FxyNERl4oKlS3hZZe4AVKjoOVhBDtgEWrS4g==";
      };
    };
    "@stdlib/streams-0.0.12" = {
      name = "_at_stdlib_slash_streams";
      packageName = "@stdlib/streams";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/streams/-/streams-0.0.12.tgz";
        sha512 = "YLUlXwjJNknHp92IkJUdvn5jEQjDckpawKhDLLCoxyh3h5V+w/8+61SH7TMTfKx5lBxKJ8vvtchZh90mIJOAjQ==";
      };
    };
    "@stdlib/strided-0.0.12" = {
      name = "_at_stdlib_slash_strided";
      packageName = "@stdlib/strided";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/strided/-/strided-0.0.12.tgz";
        sha512 = "1NINP+Y7IJht34iri/bYLY7TVxrip51f6Z3qWxGHUCH33kvk5H5QqV+RsmFEGbbyoGtdeHrT2O+xA+7R2e3SNg==";
      };
    };
    "@stdlib/string-0.0.14" = {
      name = "_at_stdlib_slash_string";
      packageName = "@stdlib/string";
      version = "0.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/string/-/string-0.0.14.tgz";
        sha512 = "1ClvUTPysens7GZz3WsrkFYIFs8qDmnXkyAd3zMvTXgRpy7hqrv6nNzLMQj8BHv5cBWaWPOXYd/cZ+JyMnZNQQ==";
      };
    };
    "@stdlib/symbol-0.0.12" = {
      name = "_at_stdlib_slash_symbol";
      packageName = "@stdlib/symbol";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/symbol/-/symbol-0.0.12.tgz";
        sha512 = "2IDhpzWVGeLHgsvIsX12RXvf78r7xBkc4QLoRUv3k7Cp61BisR1Ym1p0Tq9PbxT8fknlvLToh9n5RpmESi2d4w==";
      };
    };
    "@stdlib/time-0.0.14" = {
      name = "_at_stdlib_slash_time";
      packageName = "@stdlib/time";
      version = "0.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/time/-/time-0.0.14.tgz";
        sha512 = "1gMFCQTabMVIgww+k4g8HHHIhyy1tIlvwT8mC0BHW7Q7TzDAgobwL0bvor+lwvCb5LlDAvNQEpaRgVT99QWGeQ==";
      };
    };
    "@stdlib/types-0.0.14" = {
      name = "_at_stdlib_slash_types";
      packageName = "@stdlib/types";
      version = "0.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/types/-/types-0.0.14.tgz";
        sha512 = "AP3EI9/il/xkwUazcoY+SbjtxHRrheXgSbWZdEGD+rWpEgj6n2i63hp6hTOpAB5NipE0tJwinQlDGOuQ1lCaCw==";
      };
    };
    "@stdlib/utils-0.0.12" = {
      name = "_at_stdlib_slash_utils";
      packageName = "@stdlib/utils";
      version = "0.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@stdlib/utils/-/utils-0.0.12.tgz";
        sha512 = "+JhFpl6l7RSq/xGnbWRQ5dAL90h9ONj8MViqlb7teBZFtePZLMwoRA1wssypFcJ8SFMRWQn7lPmpYVUkGwRSOg==";
      };
    };
    "complex.js-2.1.1" = {
      name = "complex.js";
      packageName = "complex.js";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/complex.js/-/complex.js-2.1.1.tgz";
        sha512 = "8njCHOTtFFLtegk6zQo0kkVX1rngygb/KQI6z1qZxlFI3scluC+LVTCFbrkWjBv4vvLlbQ9t88IPMC6k95VTTg==";
      };
    };
    "core-util-is-1.0.3" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.3.tgz";
        sha512 = "ZQBvi1DcpJ4GDqanjucZ2Hj3wEO5pZDS89BWbkcrvdxksJorwUDDZamX9ldFkp9aw2lmBDLgkObEA4DWNJ9FYQ==";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "decimal.js-10.3.1" = {
      name = "decimal.js";
      packageName = "decimal.js";
      version = "10.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/decimal.js/-/decimal.js-10.3.1.tgz";
        sha512 = "V0pfhfr8suzyPGOx3nmq4aHqabehUZn6Ch9kyFpV79TGDTWFmHqUqXdabR7QHqxzrYolF4+tVmJhUG4OURg5dQ==";
      };
    };
    "escape-latex-1.2.0" = {
      name = "escape-latex";
      packageName = "escape-latex";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-latex/-/escape-latex-1.2.0.tgz";
        sha512 = "nV5aVWW1K0wEiUIEdZ4erkGGH8mDxGyxSeqPzRNtWP7ataw+/olFObw7hujFWlVjNsaDFw5VZ5NzVSIqRgfTiw==";
      };
    };
    "fraction.js-4.2.0" = {
      name = "fraction.js";
      packageName = "fraction.js";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fraction.js/-/fraction.js-4.2.0.tgz";
        sha512 = "MhLuK+2gUcnZe8ZHlaaINnQLl0xRIGRfcGk2yl8xoQAfHrSsL3rYu6FCmBdkdbhc9EPlwyGHewaRsvwRMJtAlA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha512 = "VLghIWNM6ELQzo7zwmcg0NmTVyWKYjvIeM83yjp0wRDTmUnrM678fQbcKBo6n2CJEF0szoG//ytg+TKla89ALQ==";
      };
    };
    "javascript-natural-sort-0.7.1" = {
      name = "javascript-natural-sort";
      packageName = "javascript-natural-sort";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/javascript-natural-sort/-/javascript-natural-sort-0.7.1.tgz";
        sha512 = "nO6jcEfZWQXDhOiBtG2KvKyEptz7RVbpGP4vTD2hLBdmNQSsCiicO2Ioinv6UI4y9ukqnBpy+XZ9H6uLNgJTlw==";
      };
    };
    "jstat-1.9.5" = {
      name = "jstat";
      packageName = "jstat";
      version = "1.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/jstat/-/jstat-1.9.5.tgz";
        sha512 = "cWnp4vObF5GmB2XsIEzxI/1ZTcYlcfNqxQ/9Fp5KFUa0Jf/4tO0ZkGVnqoEHDisJvYgvn5n3eWZbd2xTVJJPUQ==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "mathjs-11.0.1" = {
      name = "mathjs";
      packageName = "mathjs";
      version = "11.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mathjs/-/mathjs-11.0.1.tgz";
        sha512 = "Kgm+GcTxwD68zupr7BPK0yrlWpTh2q8sMH6VcBcQe5+JCBqcwOrBxBF11WPah7hVv0NCLDnJnFTiXtik1Phasg==";
      };
    };
    "minimist-1.2.6" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.6.tgz";
        sha512 = "Jsjnk4bw3YJqYzbdyBiNsPWHPfO++UGG749Cxs6peCu5Xg4nrena6OVxOYxrQTqww0Jmwt+Ref8rggumkTLz9Q==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha512 = "Tpp60P6IUJDTuOq/5Z8cdskzJujfwqfOTkrwIwj7IRISpnkJnT6SyJ4PCPnGMoFjC9ddhal5KVIYtAt97ix05A==";
      };
    };
    "pdfast-0.2.0" = {
      name = "pdfast";
      packageName = "pdfast";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pdfast/-/pdfast-0.2.0.tgz";
        sha512 = "cq6TTu6qKSFUHwEahi68k/kqN2mfepjkGrG9Un70cgdRRKLKY6Rf8P8uvP2NvZktaQZNF3YE7agEkLj0vGK9bA==";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "readable-stream-2.3.7" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.7.tgz";
        sha512 = "Ebho8K4jIbHAxnuxi7o42OrZgF/ZTNcsZj6nRKyUmkhLFq8CHItp/fy6hQZuZmP/n3yZ9VBUbp4zz/mX8hmYPw==";
      };
    };
    "regenerator-runtime-0.13.9" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.9.tgz";
        sha512 = "p3VT+cOEgxFsRRA9X4lkI1E+k2/CtnKtU4gcxyaCUreilL/vqI6CdZ3wxVUx3UOUg+gnUOQQcRI7BmSI656MYA==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "seedrandom-3.0.5" = {
      name = "seedrandom";
      packageName = "seedrandom";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/seedrandom/-/seedrandom-3.0.5.tgz";
        sha512 = "8OwmbklUNzwezjGInmZ+2clQmExQPvomqjL7LFqOYqtmuxRgQYqOD3mHaU+MvZn5FLUeVxVfQjwLZW/n/JFuqg==";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "tiny-emitter-2.1.0" = {
      name = "tiny-emitter";
      packageName = "tiny-emitter";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-emitter/-/tiny-emitter-2.1.0.tgz";
        sha512 = "NB6Dk1A9xgQPMoGqC5CVXn123gWyte215ONT5Pp5a0yt4nlEoO1ZWeCwpncaekPHXO60i47ihFnZPiRPjRMq4Q==";
      };
    };
    "typed-function-3.0.0" = {
      name = "typed-function";
      packageName = "typed-function";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-function/-/typed-function-3.0.0.tgz";
        sha512 = "mKJKkt2xYxJUuMD7jyfgUxfn5KCsCxkEKBVjep5yYellJJ5aEDO2QUAmIGdvcZmfQnIrplkzELIaG+5b1475qg==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
  };
  args = {
    name = "_at_quri_slash_squiggle-lang";
    packageName = "@quri/squiggle-lang";
    version = "0.2.11";
    src = ./.;
    dependencies = [
      sources."@babel/runtime-7.18.9"
      sources."@rescript/std-9.1.4"
      sources."@stdlib/array-0.0.12"
      sources."@stdlib/assert-0.0.12"
      sources."@stdlib/bigint-0.0.11"
      sources."@stdlib/blas-0.0.12"
      sources."@stdlib/buffer-0.0.11"
      sources."@stdlib/cli-0.0.10"
      sources."@stdlib/complex-0.0.12"
      sources."@stdlib/constants-0.0.11"
      sources."@stdlib/fs-0.0.12"
      sources."@stdlib/math-0.0.11"
      sources."@stdlib/ndarray-0.0.13"
      sources."@stdlib/nlp-0.0.11"
      sources."@stdlib/number-0.0.10"
      sources."@stdlib/os-0.0.12"
      sources."@stdlib/process-0.0.12"
      sources."@stdlib/random-0.0.12"
      sources."@stdlib/regexp-0.0.13"
      sources."@stdlib/stats-0.0.13"
      sources."@stdlib/streams-0.0.12"
      sources."@stdlib/strided-0.0.12"
      sources."@stdlib/string-0.0.14"
      sources."@stdlib/symbol-0.0.12"
      sources."@stdlib/time-0.0.14"
      sources."@stdlib/types-0.0.14"
      sources."@stdlib/utils-0.0.12"
      sources."complex.js-2.1.1"
      sources."core-util-is-1.0.3"
      sources."debug-2.6.9"
      sources."decimal.js-10.3.1"
      sources."escape-latex-1.2.0"
      sources."fraction.js-4.2.0"
      sources."inherits-2.0.4"
      sources."isarray-1.0.0"
      sources."javascript-natural-sort-0.7.1"
      sources."jstat-1.9.5"
      sources."lodash-4.17.21"
      sources."mathjs-11.0.1"
      sources."minimist-1.2.6"
      sources."ms-2.0.0"
      sources."pdfast-0.2.0"
      sources."process-nextick-args-2.0.1"
      sources."readable-stream-2.3.7"
      sources."regenerator-runtime-0.13.9"
      sources."safe-buffer-5.1.2"
      sources."seedrandom-3.0.5"
      sources."string_decoder-1.1.1"
      sources."tiny-emitter-2.1.0"
      sources."typed-function-3.0.0"
      sources."util-deprecate-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      homepage = "https://squiggle-language.com";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
